"use client";

import { useQuery } from "@tanstack/react-query";

import {
  fetchNavigation,
  type NavigationTreeItem,
  type NavigationTreeResponse,
} from "@/lib/storefront-api";

const FALLBACK_WOMEN_COLUMNS: NavigationTreeItem[] = [
  {
    id: "fallback-latest",
    title: "Latest",
    type: "editorial",
    href: "/women/latest",
    open_in_new_tab: false,
    is_title_link: true,
    show_view_all: false,
    is_featured: false,
    children: [
      {
        id: "fallback-new",
        title: "New",
        type: "editorial",
        href: "/women/latest/new",
        open_in_new_tab: false,
        is_title_link: false,
        show_view_all: false,
        is_featured: false,
        children: [],
      },
      {
        id: "fallback-summer",
        title: "Summer Styles",
        type: "editorial",
        href: "/women/latest/summer-styles",
        open_in_new_tab: false,
        is_title_link: false,
        show_view_all: false,
        is_featured: false,
        children: [],
      },
      {
        id: "fallback-classics",
        title: "Classics",
        type: "editorial",
        href: "/women/latest/classics",
        open_in_new_tab: false,
        is_title_link: false,
        show_view_all: false,
        is_featured: false,
        children: [],
      },
    ],
  },
  {
    id: "fallback-sport",
    title: "A Good Sport",
    type: "editorial",
    href: "/women/a-good-sport",
    open_in_new_tab: false,
    is_title_link: true,
    show_view_all: false,
    is_featured: true,
    children: [],
  },
  {
    id: "fallback-coats",
    title: "Coats & Jackets",
    type: "editorial",
    href: "/women/coats-jackets",
    open_in_new_tab: false,
    is_title_link: false,
    show_view_all: true,
    is_featured: false,
    children: [
      {
        id: "fb-coats",
        title: "Coats",
        type: "editorial",
        href: "/women/coats-jackets/coats",
        open_in_new_tab: false,
        is_title_link: false,
        show_view_all: false,
        is_featured: false,
        children: [],
      },
      {
        id: "fb-jackets",
        title: "Jackets",
        type: "editorial",
        href: "/women/coats-jackets/jackets",
        open_in_new_tab: false,
        is_title_link: false,
        show_view_all: false,
        is_featured: false,
        children: [],
      },
      {
        id: "fb-trench",
        title: "Trench Coats",
        type: "editorial",
        href: "/women/coats-jackets/trench-coats",
        open_in_new_tab: false,
        is_title_link: false,
        show_view_all: false,
        is_featured: false,
        children: [],
      },
      {
        id: "fb-quilted",
        title: "Quilted Jackets",
        type: "editorial",
        href: "/women/coats-jackets/quilted-jackets",
        open_in_new_tab: false,
        is_title_link: false,
        show_view_all: false,
        is_featured: false,
        children: [],
      },
      {
        id: "fb-puffer",
        title: "Puffer Jackets",
        type: "editorial",
        href: "/women/coats-jackets/puffer-jackets",
        open_in_new_tab: false,
        is_title_link: false,
        show_view_all: false,
        is_featured: false,
        children: [],
      },
      {
        id: "fb-ponchos",
        title: "Ponchos & Capes",
        type: "editorial",
        href: "/women/coats-jackets/ponchos-capes",
        open_in_new_tab: false,
        is_title_link: false,
        show_view_all: false,
        is_featured: false,
        children: [],
      },
    ],
  },
  {
    id: "fallback-clothes",
    title: "Clothes",
    type: "editorial",
    href: "/women/clothes",
    open_in_new_tab: false,
    is_title_link: false,
    show_view_all: true,
    is_featured: false,
    children: [
      {
        id: "fb-cj",
        title: "Coats & Jackets",
        type: "editorial",
        href: "/women/clothes/coats-jackets",
        open_in_new_tab: false,
        is_title_link: false,
        show_view_all: false,
        is_featured: false,
        children: [],
      },
      {
        id: "fb-knit",
        title: "Knitwear",
        type: "editorial",
        href: "/women/clothes/knitwear",
        open_in_new_tab: false,
        is_title_link: false,
        show_view_all: false,
        is_featured: false,
        children: [],
      },
      {
        id: "fb-polos",
        title: "Polos & T-shirts",
        type: "editorial",
        href: "/women/clothes/polos-t-shirts",
        open_in_new_tab: false,
        is_title_link: false,
        show_view_all: false,
        is_featured: false,
        children: [],
      },
      {
        id: "fb-shirts",
        title: "Shirts & Tops",
        type: "editorial",
        href: "/women/clothes/shirts-tops",
        open_in_new_tab: false,
        is_title_link: false,
        show_view_all: false,
        is_featured: false,
        children: [],
      },
      {
        id: "fb-dresses",
        title: "Dresses",
        type: "editorial",
        href: "/women/clothes/dresses",
        open_in_new_tab: false,
        is_title_link: false,
        show_view_all: false,
        is_featured: false,
        children: [],
      },
      {
        id: "fb-skirts",
        title: "Skirts",
        type: "editorial",
        href: "/women/clothes/skirts",
        open_in_new_tab: false,
        is_title_link: false,
        show_view_all: false,
        is_featured: false,
        children: [],
      },
      {
        id: "fb-hoodies",
        title: "Hoodies & Sweatshirts",
        type: "editorial",
        href: "/women/clothes/hoodies-sweatshirts",
        open_in_new_tab: false,
        is_title_link: false,
        show_view_all: false,
        is_featured: false,
        children: [],
      },
      {
        id: "fb-blazers",
        title: "Blazers & Tailoring",
        type: "editorial",
        href: "/women/clothes/blazers-tailoring",
        open_in_new_tab: false,
        is_title_link: false,
        show_view_all: false,
        is_featured: false,
        children: [],
      },
      {
        id: "fb-trousers",
        title: "Trousers & Shorts",
        type: "editorial",
        href: "/women/clothes/trousers-shorts",
        open_in_new_tab: false,
        is_title_link: false,
        show_view_all: false,
        is_featured: false,
        children: [],
      },
      {
        id: "fb-active",
        title: "Activewear",
        type: "editorial",
        href: "/women/clothes/activewear",
        open_in_new_tab: false,
        is_title_link: false,
        show_view_all: false,
        is_featured: false,
        children: [],
      },
      {
        id: "fb-denim",
        title: "Denim",
        type: "editorial",
        href: "/women/clothes/denim",
        open_in_new_tab: false,
        is_title_link: false,
        show_view_all: false,
        is_featured: false,
        children: [],
      },
      {
        id: "fb-swim",
        title: "Swimwear",
        type: "editorial",
        href: "/women/clothes/swimwear",
        open_in_new_tab: false,
        is_title_link: false,
        show_view_all: false,
        is_featured: false,
        children: [],
      },
    ],
  },
  {
    id: "fallback-bags",
    title: "Bags",
    type: "editorial",
    href: "/women/bags",
    open_in_new_tab: false,
    is_title_link: false,
    show_view_all: true,
    is_featured: false,
    children: [
      {
        id: "fb-mini",
        title: "Mini Bags",
        type: "editorial",
        href: "/women/bags/mini-bags",
        open_in_new_tab: false,
        is_title_link: false,
        show_view_all: false,
        is_featured: false,
        children: [],
      },
      {
        id: "fb-tote",
        title: "Tote Bags",
        type: "editorial",
        href: "/women/bags/tote-bags",
        open_in_new_tab: false,
        is_title_link: false,
        show_view_all: false,
        is_featured: false,
        children: [],
      },
      {
        id: "fb-crossbody",
        title: "Crossbody Bags",
        type: "editorial",
        href: "/women/bags/crossbody-bags",
        open_in_new_tab: false,
        is_title_link: false,
        show_view_all: false,
        is_featured: false,
        children: [],
      },
      {
        id: "fb-shoulder",
        title: "Shoulder Bags",
        type: "editorial",
        href: "/women/bags/shoulder-bags",
        open_in_new_tab: false,
        is_title_link: false,
        show_view_all: false,
        is_featured: false,
        children: [],
      },
      {
        id: "fb-top-handle",
        title: "Top Handle Bags",
        type: "editorial",
        href: "/women/bags/top-handle-bags",
        open_in_new_tab: false,
        is_title_link: false,
        show_view_all: false,
        is_featured: false,
        children: [],
      },
      {
        id: "fb-backpacks",
        title: "Backpacks",
        type: "editorial",
        href: "/women/bags/backpacks",
        open_in_new_tab: false,
        is_title_link: false,
        show_view_all: false,
        is_featured: false,
        children: [],
      },
    ],
  },
  {
    id: "fallback-shoes",
    title: "Shoes",
    type: "editorial",
    href: "/women/shoes",
    open_in_new_tab: false,
    is_title_link: false,
    show_view_all: true,
    is_featured: false,
    children: [
      {
        id: "fb-sneakers",
        title: "Sneakers",
        type: "editorial",
        href: "/women/shoes/sneakers",
        open_in_new_tab: false,
        is_title_link: false,
        show_view_all: false,
        is_featured: false,
        children: [],
      },
      {
        id: "fb-sandals",
        title: "Sandals",
        type: "editorial",
        href: "/women/shoes/sandals",
        open_in_new_tab: false,
        is_title_link: false,
        show_view_all: false,
        is_featured: false,
        children: [],
      },
      {
        id: "fb-loafers",
        title: "Loafers & Ballerinas",
        type: "editorial",
        href: "/women/shoes/loafers-ballerinas",
        open_in_new_tab: false,
        is_title_link: false,
        show_view_all: false,
        is_featured: false,
        children: [],
      },
      {
        id: "fb-boots",
        title: "Boots",
        type: "editorial",
        href: "/women/shoes/boots",
        open_in_new_tab: false,
        is_title_link: false,
        show_view_all: false,
        is_featured: false,
        children: [],
      },
      {
        id: "fb-pumps",
        title: "Pumps",
        type: "editorial",
        href: "/women/shoes/pumps",
        open_in_new_tab: false,
        is_title_link: false,
        show_view_all: false,
        is_featured: false,
        children: [],
      },
    ],
  },
  {
    id: "fallback-accessories",
    title: "Accessories",
    type: "editorial",
    href: "/women/accessories",
    open_in_new_tab: false,
    is_title_link: false,
    show_view_all: true,
    is_featured: false,
    children: [
      {
        id: "fb-scarves",
        title: "Scarves",
        type: "editorial",
        href: "/women/accessories/scarves",
        open_in_new_tab: false,
        is_title_link: false,
        show_view_all: false,
        is_featured: false,
        children: [],
      },
      {
        id: "fb-belts",
        title: "Belts",
        type: "editorial",
        href: "/women/accessories/belts",
        open_in_new_tab: false,
        is_title_link: false,
        show_view_all: false,
        is_featured: false,
        children: [],
      },
      {
        id: "fb-sunglasses",
        title: "Sunglasses",
        type: "editorial",
        href: "/women/accessories/sunglasses",
        open_in_new_tab: false,
        is_title_link: false,
        show_view_all: false,
        is_featured: false,
        children: [],
      },
      {
        id: "fb-caps",
        title: "Caps & Bucket Hats",
        type: "editorial",
        href: "/women/accessories/caps-bucket-hats",
        open_in_new_tab: false,
        is_title_link: false,
        show_view_all: false,
        is_featured: false,
        children: [],
      },
      {
        id: "fb-wallets",
        title: "Wallets & Card Cases",
        type: "editorial",
        href: "/women/accessories/wallets-card-cases",
        open_in_new_tab: false,
        is_title_link: false,
        show_view_all: false,
        is_featured: false,
        children: [],
      },
      {
        id: "fb-umbrellas",
        title: "Umbrellas",
        type: "editorial",
        href: "/women/accessories/umbrellas",
        open_in_new_tab: false,
        is_title_link: false,
        show_view_all: false,
        is_featured: false,
        children: [],
      },
      {
        id: "fb-jewellery",
        title: "Jewellery",
        type: "editorial",
        href: "/women/accessories/jewellery",
        open_in_new_tab: false,
        is_title_link: false,
        show_view_all: false,
        is_featured: false,
        children: [],
      },
      {
        id: "fb-home",
        title: "Home",
        type: "editorial",
        href: "/women/accessories/home",
        open_in_new_tab: false,
        is_title_link: false,
        show_view_all: false,
        is_featured: false,
        children: [],
      },
      {
        id: "fb-socks",
        title: "Socks & Tights",
        type: "editorial",
        href: "/women/accessories/socks-tights",
        open_in_new_tab: false,
        is_title_link: false,
        show_view_all: false,
        is_featured: false,
        children: [],
      },
      {
        id: "fb-tech",
        title: "Tech & Travel",
        type: "editorial",
        href: "/women/accessories/tech-travel",
        open_in_new_tab: false,
        is_title_link: false,
        show_view_all: false,
        is_featured: false,
        children: [],
      },
      {
        id: "fb-charms",
        title: "Key & Bag Charms",
        type: "editorial",
        href: "/women/accessories/key-bag-charms",
        open_in_new_tab: false,
        is_title_link: false,
        show_view_all: false,
        is_featured: false,
        children: [],
      },
    ],
  },
  {
    id: "fallback-wallets2",
    title: "Wallets & Card Cases",
    type: "editorial",
    href: "/women/wallets-card-cases",
    open_in_new_tab: false,
    is_title_link: false,
    show_view_all: true,
    is_featured: false,
    children: [
      {
        id: "fb-card-cases",
        title: "Card Cases",
        type: "editorial",
        href: "/women/wallets-card-cases/card-cases",
        open_in_new_tab: false,
        is_title_link: false,
        show_view_all: false,
        is_featured: false,
        children: [],
      },
      {
        id: "fb-long",
        title: "Long Wallets",
        type: "editorial",
        href: "/women/wallets-card-cases/long-wallets",
        open_in_new_tab: false,
        is_title_link: false,
        show_view_all: false,
        is_featured: false,
        children: [],
      },
      {
        id: "fb-compact",
        title: "Compact Wallets",
        type: "editorial",
        href: "/women/wallets-card-cases/compact-wallets",
        open_in_new_tab: false,
        is_title_link: false,
        show_view_all: false,
        is_featured: false,
        children: [],
      },
      {
        id: "fb-chain",
        title: "Chain Strap Wallets",
        type: "editorial",
        href: "/women/wallets-card-cases/chain-strap-wallets",
        open_in_new_tab: false,
        is_title_link: false,
        show_view_all: false,
        is_featured: false,
        children: [],
      },
    ],
  },
  {
    id: "fallback-gifts",
    title: "Gifts",
    type: "editorial",
    href: "/women/gifts",
    open_in_new_tab: false,
    is_title_link: false,
    show_view_all: true,
    is_featured: false,
    children: [
      {
        id: "fb-fragrance",
        title: "Fragrance",
        type: "editorial",
        href: "/women/gifts/fragrance",
        open_in_new_tab: false,
        is_title_link: false,
        show_view_all: false,
        is_featured: false,
        children: [],
      },
      {
        id: "fb-personalised",
        title: "Personalised Gifts",
        type: "editorial",
        href: "/women/gifts/personalised-gifts",
        open_in_new_tab: false,
        is_title_link: false,
        show_view_all: false,
        is_featured: false,
        children: [],
      },
      {
        id: "fb-personalised-scarves",
        title: "Personalised Scarves",
        type: "editorial",
        href: "/women/gifts/personalised-scarves",
        open_in_new_tab: false,
        is_title_link: false,
        show_view_all: false,
        is_featured: false,
        children: [],
      },
      {
        id: "fb-classics",
        title: "Burberry Classics",
        type: "editorial",
        href: "/women/gifts/burberry-classics",
        open_in_new_tab: false,
        is_title_link: false,
        show_view_all: false,
        is_featured: false,
        children: [],
      },
    ],
  },
];

const FALLBACK_TOP_LEVEL: NavigationTreeItem[] = [
  {
    id: "fallback-men",
    title: "Men",
    type: "editorial",
    href: "/men",
    open_in_new_tab: false,
    is_title_link: false,
    show_view_all: false,
    is_featured: false,
    children: [],
  },
  {
    id: "fallback-children",
    title: "Children",
    type: "editorial",
    href: "/children",
    open_in_new_tab: false,
    is_title_link: false,
    show_view_all: false,
    is_featured: false,
    children: [],
  },
  {
    id: "fallback-gifts2",
    title: "Gifts",
    type: "editorial",
    href: "/gifts",
    open_in_new_tab: false,
    is_title_link: false,
    show_view_all: false,
    is_featured: false,
    children: [],
  },
  {
    id: "fallback-trench",
    title: "Trench",
    type: "editorial",
    href: "/trench",
    open_in_new_tab: false,
    is_title_link: false,
    show_view_all: false,
    is_featured: false,
    children: [],
  },
  {
    id: "fallback-scarves2",
    title: "Scarves",
    type: "editorial",
    href: "/scarves",
    open_in_new_tab: false,
    is_title_link: false,
    show_view_all: false,
    is_featured: false,
    children: [],
  },
  {
    id: "fallback-bags2",
    title: "Bags",
    type: "editorial",
    href: "/bags",
    open_in_new_tab: false,
    is_title_link: false,
    show_view_all: false,
    is_featured: false,
    children: [],
  },
  {
    id: "fallback-beauty",
    title: "Beauty",
    type: "editorial",
    href: "/beauty",
    open_in_new_tab: false,
    is_title_link: false,
    show_view_all: false,
    is_featured: false,
    children: [],
  },
];

interface NavData {
  womenColumns: NavigationTreeItem[];
  topLevel: NavigationTreeItem[];
}

export function useNavigation(tenant?: string | null) {
  return useQuery<NavigationTreeResponse | null, Error, NavData>({
    queryKey: ["navigation", "main", tenant],
    queryFn: () => (tenant ? fetchNavigation(tenant) : null),
    select: (data) => {
      if (!data) {
        return {
          womenColumns: FALLBACK_WOMEN_COLUMNS,
          topLevel: FALLBACK_TOP_LEVEL,
        };
      }
      const womenItem = data.items.find(
        (i: NavigationTreeItem) => i.title === "Women",
      );
      return {
        womenColumns: womenItem?.children ?? [],
        topLevel: data.items.filter(
          (i: NavigationTreeItem) => i.title !== "Women",
        ),
      };
    },
    enabled: !!tenant,
    staleTime: 5 * 60 * 1000,
    placeholderData: (
      previousData: NavigationTreeResponse | null | undefined,
    ) => previousData ?? null,
  });
}
