// This file is auto-generated by @hey-api/openapi-ts

import type {
  Client,
  ClientMeta,
  Options as Options2,
  RequestResult,
  TDataShape,
} from "./client";
import { client } from "./client.gen";
import type {
  AddCartItemApiV1StorefrontTenantSlugCartsCartIdItemsPostData,
  AddCartItemApiV1StorefrontTenantSlugCartsCartIdItemsPostErrors,
  AddCartItemApiV1StorefrontTenantSlugCartsCartIdItemsPostResponses,
  AddProductsToCollectionApiV1CollectionsCollectionIdProductsPostData,
  AddProductsToCollectionApiV1CollectionsCollectionIdProductsPostErrors,
  AddProductsToCollectionApiV1CollectionsCollectionIdProductsPostResponses,
  ApprovePurchaseOrderApiV1PurchaseOrdersPoIdApprovePostData,
  ApprovePurchaseOrderApiV1PurchaseOrdersPoIdApprovePostErrors,
  ApprovePurchaseOrderApiV1PurchaseOrdersPoIdApprovePostResponses,
  CancelPurchaseOrderApiV1PurchaseOrdersPoIdCancelPostData,
  CancelPurchaseOrderApiV1PurchaseOrdersPoIdCancelPostErrors,
  CancelPurchaseOrderApiV1PurchaseOrdersPoIdCancelPostResponses,
  CheckoutApiV1StorefrontTenantSlugCartsCartIdCheckoutPostData,
  CheckoutApiV1StorefrontTenantSlugCartsCartIdCheckoutPostErrors,
  CheckoutApiV1StorefrontTenantSlugCartsCartIdCheckoutPostResponses,
  ClearCartApiV1StorefrontTenantSlugCartsCartIdDeleteData,
  ClearCartApiV1StorefrontTenantSlugCartsCartIdDeleteErrors,
  ClearCartApiV1StorefrontTenantSlugCartsCartIdDeleteResponses,
  CreateCartApiV1StorefrontTenantSlugCartsPostData,
  CreateCartApiV1StorefrontTenantSlugCartsPostErrors,
  CreateCartApiV1StorefrontTenantSlugCartsPostResponses,
  CreateCategoryApiV1CategoriesPostData,
  CreateCategoryApiV1CategoriesPostErrors,
  CreateCategoryApiV1CategoriesPostResponses,
  CreateCollectionApiV1CollectionsPostData,
  CreateCollectionApiV1CollectionsPostErrors,
  CreateCollectionApiV1CollectionsPostResponses,
  CreateItemApiV1InventoryPostData,
  CreateItemApiV1InventoryPostErrors,
  CreateItemApiV1InventoryPostResponses,
  CreateOrderApiV1OrdersPostData,
  CreateOrderApiV1OrdersPostErrors,
  CreateOrderApiV1OrdersPostResponses,
  CreateProductApiV1ProductsPostData,
  CreateProductApiV1ProductsPostErrors,
  CreateProductApiV1ProductsPostResponses,
  CreateProductImageApiV1ProductsProductIdImagesPostData,
  CreateProductImageApiV1ProductsProductIdImagesPostErrors,
  CreateProductImageApiV1ProductsProductIdImagesPostResponses,
  CreateSupplierApiV1SuppliersPostData,
  CreateSupplierApiV1SuppliersPostErrors,
  CreateSupplierApiV1SuppliersPostResponses,
  CreateTenantApiV1TenantsPostData,
  CreateTenantApiV1TenantsPostErrors,
  CreateTenantApiV1TenantsPostResponses,
  CreateVariantApiV1ProductsProductIdVariantsPostData,
  CreateVariantApiV1ProductsProductIdVariantsPostErrors,
  CreateVariantApiV1ProductsProductIdVariantsPostResponses,
  DashboardSummaryApiV1AdminDashboardSummaryGetData,
  DashboardSummaryApiV1AdminDashboardSummaryGetErrors,
  DashboardSummaryApiV1AdminDashboardSummaryGetResponses,
  DeleteCategoryApiV1CategoriesCategoryIdDeleteData,
  DeleteCategoryApiV1CategoriesCategoryIdDeleteErrors,
  DeleteCategoryApiV1CategoriesCategoryIdDeleteResponses,
  DeleteCollectionApiV1CollectionsCollectionIdDeleteData,
  DeleteCollectionApiV1CollectionsCollectionIdDeleteErrors,
  DeleteCollectionApiV1CollectionsCollectionIdDeleteResponses,
  DeleteItemApiV1InventoryItemIdDeleteData,
  DeleteItemApiV1InventoryItemIdDeleteErrors,
  DeleteItemApiV1InventoryItemIdDeleteResponses,
  DeleteProductApiV1ProductsProductIdDeleteData,
  DeleteProductApiV1ProductsProductIdDeleteErrors,
  DeleteProductApiV1ProductsProductIdDeleteResponses,
  DeleteProductImageApiV1ProductImagesImageIdDeleteData,
  DeleteProductImageApiV1ProductImagesImageIdDeleteErrors,
  DeleteProductImageApiV1ProductImagesImageIdDeleteResponses,
  DeleteSupplierApiV1SuppliersSupplierIdDeleteData,
  DeleteSupplierApiV1SuppliersSupplierIdDeleteErrors,
  DeleteSupplierApiV1SuppliersSupplierIdDeleteResponses,
  DeleteTenantApiV1TenantsTenantIdDeleteData,
  DeleteTenantApiV1TenantsTenantIdDeleteErrors,
  DeleteTenantApiV1TenantsTenantIdDeleteResponses,
  DeleteVariantApiV1ProductsProductIdVariantsVariantIdDeleteData,
  DeleteVariantApiV1ProductsProductIdVariantsVariantIdDeleteErrors,
  DeleteVariantApiV1ProductsProductIdVariantsVariantIdDeleteResponses,
  GetCartApiV1StorefrontTenantSlugCartsCartIdGetData,
  GetCartApiV1StorefrontTenantSlugCartsCartIdGetErrors,
  GetCartApiV1StorefrontTenantSlugCartsCartIdGetResponses,
  GetCustomerApiV1CustomersCustomerIdGetData,
  GetCustomerApiV1CustomersCustomerIdGetErrors,
  GetCustomerApiV1CustomersCustomerIdGetResponses,
  GetItemApiV1InventoryItemIdGetData,
  GetItemApiV1InventoryItemIdGetErrors,
  GetItemApiV1InventoryItemIdGetResponses,
  GetOrderApiV1OrdersOrderIdGetData,
  GetOrderApiV1OrdersOrderIdGetErrors,
  GetOrderApiV1OrdersOrderIdGetResponses,
  GetOrderPurchaseOrdersApiV1OrdersOrderIdPurchaseOrdersGetData,
  GetOrderPurchaseOrdersApiV1OrdersOrderIdPurchaseOrdersGetErrors,
  GetOrderPurchaseOrdersApiV1OrdersOrderIdPurchaseOrdersGetResponses,
  GetProductApiV1ProductsProductIdGetData,
  GetProductApiV1ProductsProductIdGetErrors,
  GetProductApiV1ProductsProductIdGetResponses,
  GetPurchaseOrderApiV1PurchaseOrdersPoIdGetData,
  GetPurchaseOrderApiV1PurchaseOrdersPoIdGetErrors,
  GetPurchaseOrderApiV1PurchaseOrdersPoIdGetResponses,
  GetStatsApiV1InventoryStatsGetData,
  GetStatsApiV1InventoryStatsGetErrors,
  GetStatsApiV1InventoryStatsGetResponses,
  GetStorefrontProductApiV1StorefrontTenantSlugProductsProductSlugGetData,
  GetStorefrontProductApiV1StorefrontTenantSlugProductsProductSlugGetErrors,
  GetStorefrontProductApiV1StorefrontTenantSlugProductsProductSlugGetResponses,
  GetSupplierApiV1SuppliersSupplierIdGetData,
  GetSupplierApiV1SuppliersSupplierIdGetErrors,
  GetSupplierApiV1SuppliersSupplierIdGetResponses,
  GetTenantApiV1TenantsTenantIdGetData,
  GetTenantApiV1TenantsTenantIdGetErrors,
  GetTenantApiV1TenantsTenantIdGetResponses,
  GetTenantSettingsApiV1StorefrontTenantSlugSettingsGetData,
  GetTenantSettingsApiV1StorefrontTenantSlugSettingsGetErrors,
  GetTenantSettingsApiV1StorefrontTenantSlugSettingsGetResponses,
  GetVariantApiV1ProductsProductIdVariantsVariantIdGetData,
  GetVariantApiV1ProductsProductIdVariantsVariantIdGetErrors,
  GetVariantApiV1ProductsProductIdVariantsVariantIdGetResponses,
  HealthHealthGetData,
  HealthHealthGetResponses,
  ListCategoriesApiV1CategoriesGetData,
  ListCategoriesApiV1CategoriesGetErrors,
  ListCategoriesApiV1CategoriesGetResponses,
  ListCollectionProductsApiV1CollectionsCollectionIdProductsGetData,
  ListCollectionProductsApiV1CollectionsCollectionIdProductsGetErrors,
  ListCollectionProductsApiV1CollectionsCollectionIdProductsGetResponses,
  ListCollectionsApiV1CollectionsGetData,
  ListCollectionsApiV1CollectionsGetErrors,
  ListCollectionsApiV1CollectionsGetResponses,
  ListCustomersApiV1CustomersGetData,
  ListCustomersApiV1CustomersGetErrors,
  ListCustomersApiV1CustomersGetResponses,
  ListItemsApiV1InventoryGetData,
  ListItemsApiV1InventoryGetErrors,
  ListItemsApiV1InventoryGetResponses,
  ListOrdersApiV1OrdersGetData,
  ListOrdersApiV1OrdersGetErrors,
  ListOrdersApiV1OrdersGetResponses,
  ListPendingOrdersApiV1PurchaseOrdersPendingGetData,
  ListPendingOrdersApiV1PurchaseOrdersPendingGetErrors,
  ListPendingOrdersApiV1PurchaseOrdersPendingGetResponses,
  ListProductsApiV1ProductsGetData,
  ListProductsApiV1ProductsGetErrors,
  ListProductsApiV1ProductsGetResponses,
  ListPurchaseOrdersApiV1PurchaseOrdersGetData,
  ListPurchaseOrdersApiV1PurchaseOrdersGetErrors,
  ListPurchaseOrdersApiV1PurchaseOrdersGetResponses,
  ListStorefrontProductsApiV1StorefrontTenantSlugProductsGetData,
  ListStorefrontProductsApiV1StorefrontTenantSlugProductsGetErrors,
  ListStorefrontProductsApiV1StorefrontTenantSlugProductsGetResponses,
  ListSuppliersApiV1SuppliersGetData,
  ListSuppliersApiV1SuppliersGetErrors,
  ListSuppliersApiV1SuppliersGetResponses,
  ListTenantsApiV1TenantsGetData,
  ListTenantsApiV1TenantsGetResponses,
  ListVariantsApiV1ProductsProductIdVariantsGetData,
  ListVariantsApiV1ProductsProductIdVariantsGetErrors,
  ListVariantsApiV1ProductsProductIdVariantsGetResponses,
  LoginAdminAuthLoginPostData,
  LoginAdminAuthLoginPostErrors,
  LoginAdminAuthLoginPostResponses,
  LoginAuthLoginPostData,
  LoginAuthLoginPostErrors,
  LoginAuthLoginPostResponses,
  LogoutAdminAuthLogoutPostData,
  LogoutAdminAuthLogoutPostResponses,
  LogoutAuthLogoutPostData,
  LogoutAuthLogoutPostResponses,
  MeAdminAuthMeGetData,
  MeAdminAuthMeGetResponses,
  PatchOrderApiV1OrdersOrderIdPatchData,
  PatchOrderApiV1OrdersOrderIdPatchErrors,
  PatchOrderApiV1OrdersOrderIdPatchResponses,
  PublicCategoriesApiV1PublicCategoriesTenantSlugGetData,
  PublicCategoriesApiV1PublicCategoriesTenantSlugGetErrors,
  PublicCategoriesApiV1PublicCategoriesTenantSlugGetResponses,
  PublicCollectionsApiV1PublicCollectionsTenantSlugGetData,
  PublicCollectionsApiV1PublicCollectionsTenantSlugGetErrors,
  PublicCollectionsApiV1PublicCollectionsTenantSlugGetResponses,
  PublicProductsApiV1PublicProductsTenantSlugGetData,
  PublicProductsApiV1PublicProductsTenantSlugGetErrors,
  PublicProductsApiV1PublicProductsTenantSlugGetResponses,
  RefreshAdminAuthRefreshPostData,
  RefreshAdminAuthRefreshPostErrors,
  RefreshAdminAuthRefreshPostResponses,
  RefreshTokenAuthRefreshPostData,
  RefreshTokenAuthRefreshPostResponses,
  RegisterAdminAuthRegisterPostData,
  RegisterAdminAuthRegisterPostErrors,
  RegisterAdminAuthRegisterPostResponses,
  RegisterAuthRegisterPostData,
  RegisterAuthRegisterPostErrors,
  RegisterAuthRegisterPostResponses,
  RemoveCartItemApiV1StorefrontTenantSlugCartsCartIdItemsItemIdDeleteData,
  RemoveCartItemApiV1StorefrontTenantSlugCartsCartIdItemsItemIdDeleteErrors,
  RemoveCartItemApiV1StorefrontTenantSlugCartsCartIdItemsItemIdDeleteResponses,
  RemoveProductFromCollectionApiV1CollectionsCollectionIdProductsProductIdDeleteData,
  RemoveProductFromCollectionApiV1CollectionsCollectionIdProductsProductIdDeleteErrors,
  RemoveProductFromCollectionApiV1CollectionsCollectionIdProductsProductIdDeleteResponses,
  ResolveTenantApiV1PublicTenantsSlugGetData,
  ResolveTenantApiV1PublicTenantsSlugGetErrors,
  ResolveTenantApiV1PublicTenantsSlugGetResponses,
  ShopifyWebhookWebhooksShopifyPostData,
  ShopifyWebhookWebhooksShopifyPostErrors,
  ShopifyWebhookWebhooksShopifyPostResponses,
  SvixWebhookWebhooksSvixPostData,
  SvixWebhookWebhooksSvixPostErrors,
  SvixWebhookWebhooksSvixPostResponses,
  UpdateCartItemApiV1StorefrontTenantSlugCartsCartIdItemsItemIdPatchData,
  UpdateCartItemApiV1StorefrontTenantSlugCartsCartIdItemsItemIdPatchErrors,
  UpdateCartItemApiV1StorefrontTenantSlugCartsCartIdItemsItemIdPatchResponses,
  UpdateCategoryApiV1CategoriesCategoryIdPutData,
  UpdateCategoryApiV1CategoriesCategoryIdPutErrors,
  UpdateCategoryApiV1CategoriesCategoryIdPutResponses,
  UpdateCollectionApiV1CollectionsCollectionIdPutData,
  UpdateCollectionApiV1CollectionsCollectionIdPutErrors,
  UpdateCollectionApiV1CollectionsCollectionIdPutResponses,
  UpdateItemApiV1InventoryItemIdPatchData,
  UpdateItemApiV1InventoryItemIdPatchErrors,
  UpdateItemApiV1InventoryItemIdPatchResponses,
  UpdateOrderApiV1OrdersOrderIdPutData,
  UpdateOrderApiV1OrdersOrderIdPutErrors,
  UpdateOrderApiV1OrdersOrderIdPutResponses,
  UpdateProductApiV1ProductsProductIdPutData,
  UpdateProductApiV1ProductsProductIdPutErrors,
  UpdateProductApiV1ProductsProductIdPutResponses,
  UpdateProductImageApiV1ProductImagesImageIdPatchData,
  UpdateProductImageApiV1ProductImagesImageIdPatchErrors,
  UpdateProductImageApiV1ProductImagesImageIdPatchResponses,
  UpdatePurchaseOrderApiV1PurchaseOrdersPoIdPatchData,
  UpdatePurchaseOrderApiV1PurchaseOrdersPoIdPatchErrors,
  UpdatePurchaseOrderApiV1PurchaseOrdersPoIdPatchResponses,
  UpdateSupplierApiV1SuppliersSupplierIdPatchData,
  UpdateSupplierApiV1SuppliersSupplierIdPatchErrors,
  UpdateSupplierApiV1SuppliersSupplierIdPatchResponses,
  UpdateTenantApiV1TenantsTenantIdPutData,
  UpdateTenantApiV1TenantsTenantIdPutErrors,
  UpdateTenantApiV1TenantsTenantIdPutResponses,
  UpdateVariantApiV1ProductsProductIdVariantsVariantIdPutData,
  UpdateVariantApiV1ProductsProductIdVariantsVariantIdPutErrors,
  UpdateVariantApiV1ProductsProductIdVariantsVariantIdPutResponses,
  UploadSignatureApiV1MediaUploadSignaturePostData,
  UploadSignatureApiV1MediaUploadSignaturePostResponses,
  VerifyAdminAuthVerifyPostData,
  VerifyAdminAuthVerifyPostResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Resolve Tenant
 *
 * Resolve a tenant by slug — used by the storefront to discover tenant info.
 */
export const resolveTenantApiV1PublicTenantsSlugGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ResolveTenantApiV1PublicTenantsSlugGetData, ThrowOnError>,
): RequestResult<
  ResolveTenantApiV1PublicTenantsSlugGetResponses,
  ResolveTenantApiV1PublicTenantsSlugGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ResolveTenantApiV1PublicTenantsSlugGetResponses,
    ResolveTenantApiV1PublicTenantsSlugGetErrors,
    ThrowOnError
  >({ url: "/api/v1/public/tenants/{slug}", ...options });

/**
 * Public Products
 *
 * List active products for a tenant — public storefront browsing.
 */
export const publicProductsApiV1PublicProductsTenantSlugGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    PublicProductsApiV1PublicProductsTenantSlugGetData,
    ThrowOnError
  >,
): RequestResult<
  PublicProductsApiV1PublicProductsTenantSlugGetResponses,
  PublicProductsApiV1PublicProductsTenantSlugGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    PublicProductsApiV1PublicProductsTenantSlugGetResponses,
    PublicProductsApiV1PublicProductsTenantSlugGetErrors,
    ThrowOnError
  >({ url: "/api/v1/public/products/{tenant_slug}", ...options });

/**
 * Public Categories
 *
 * List active categories for a tenant — public storefront browsing.
 */
export const publicCategoriesApiV1PublicCategoriesTenantSlugGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    PublicCategoriesApiV1PublicCategoriesTenantSlugGetData,
    ThrowOnError
  >,
): RequestResult<
  PublicCategoriesApiV1PublicCategoriesTenantSlugGetResponses,
  PublicCategoriesApiV1PublicCategoriesTenantSlugGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    PublicCategoriesApiV1PublicCategoriesTenantSlugGetResponses,
    PublicCategoriesApiV1PublicCategoriesTenantSlugGetErrors,
    ThrowOnError
  >({ url: "/api/v1/public/categories/{tenant_slug}", ...options });

/**
 * Public Collections
 *
 * List active collections for a tenant — public storefront browsing.
 */
export const publicCollectionsApiV1PublicCollectionsTenantSlugGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    PublicCollectionsApiV1PublicCollectionsTenantSlugGetData,
    ThrowOnError
  >,
): RequestResult<
  PublicCollectionsApiV1PublicCollectionsTenantSlugGetResponses,
  PublicCollectionsApiV1PublicCollectionsTenantSlugGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    PublicCollectionsApiV1PublicCollectionsTenantSlugGetResponses,
    PublicCollectionsApiV1PublicCollectionsTenantSlugGetErrors,
    ThrowOnError
  >({ url: "/api/v1/public/collections/{tenant_slug}", ...options });

/**
 * List Storefront Products
 *
 * Paginated list of published products for storefront PLP.
 */
export const listStorefrontProductsApiV1StorefrontTenantSlugProductsGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ListStorefrontProductsApiV1StorefrontTenantSlugProductsGetData,
    ThrowOnError
  >,
): RequestResult<
  ListStorefrontProductsApiV1StorefrontTenantSlugProductsGetResponses,
  ListStorefrontProductsApiV1StorefrontTenantSlugProductsGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListStorefrontProductsApiV1StorefrontTenantSlugProductsGetResponses,
    ListStorefrontProductsApiV1StorefrontTenantSlugProductsGetErrors,
    ThrowOnError
  >({ url: "/api/v1/storefront/{tenant_slug}/products", ...options });

/**
 * Get Storefront Product
 *
 * Single product detail for storefront PDP.
 */
export const getStorefrontProductApiV1StorefrontTenantSlugProductsProductSlugGet =
  <ThrowOnError extends boolean = false>(
    options: Options<
      GetStorefrontProductApiV1StorefrontTenantSlugProductsProductSlugGetData,
      ThrowOnError
    >,
  ): RequestResult<
    GetStorefrontProductApiV1StorefrontTenantSlugProductsProductSlugGetResponses,
    GetStorefrontProductApiV1StorefrontTenantSlugProductsProductSlugGetErrors,
    ThrowOnError
  > =>
    (options.client ?? client).get<
      GetStorefrontProductApiV1StorefrontTenantSlugProductsProductSlugGetResponses,
      GetStorefrontProductApiV1StorefrontTenantSlugProductsProductSlugGetErrors,
      ThrowOnError
    >({
      url: "/api/v1/storefront/{tenant_slug}/products/{product_slug}",
      ...options,
    });

/**
 * Get Tenant Settings
 *
 * Public tenant settings — store name, currency, theme preferences.
 */
export const getTenantSettingsApiV1StorefrontTenantSlugSettingsGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetTenantSettingsApiV1StorefrontTenantSlugSettingsGetData,
    ThrowOnError
  >,
): RequestResult<
  GetTenantSettingsApiV1StorefrontTenantSlugSettingsGetResponses,
  GetTenantSettingsApiV1StorefrontTenantSlugSettingsGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetTenantSettingsApiV1StorefrontTenantSlugSettingsGetResponses,
    GetTenantSettingsApiV1StorefrontTenantSlugSettingsGetErrors,
    ThrowOnError
  >({ url: "/api/v1/storefront/{tenant_slug}/settings", ...options });

/**
 * Create Cart
 *
 * Create a new cart with the first item.
 */
export const createCartApiV1StorefrontTenantSlugCartsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    CreateCartApiV1StorefrontTenantSlugCartsPostData,
    ThrowOnError
  >,
): RequestResult<
  CreateCartApiV1StorefrontTenantSlugCartsPostResponses,
  CreateCartApiV1StorefrontTenantSlugCartsPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateCartApiV1StorefrontTenantSlugCartsPostResponses,
    CreateCartApiV1StorefrontTenantSlugCartsPostErrors,
    ThrowOnError
  >({
    url: "/api/v1/storefront/{tenant_slug}/carts",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Clear Cart
 *
 * Clear all items from the cart.
 */
export const clearCartApiV1StorefrontTenantSlugCartsCartIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ClearCartApiV1StorefrontTenantSlugCartsCartIdDeleteData,
    ThrowOnError
  >,
): RequestResult<
  ClearCartApiV1StorefrontTenantSlugCartsCartIdDeleteResponses,
  ClearCartApiV1StorefrontTenantSlugCartsCartIdDeleteErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    ClearCartApiV1StorefrontTenantSlugCartsCartIdDeleteResponses,
    ClearCartApiV1StorefrontTenantSlugCartsCartIdDeleteErrors,
    ThrowOnError
  >({ url: "/api/v1/storefront/{tenant_slug}/carts/{cart_id}", ...options });

/**
 * Get Cart
 *
 * Get cart contents.
 */
export const getCartApiV1StorefrontTenantSlugCartsCartIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetCartApiV1StorefrontTenantSlugCartsCartIdGetData,
    ThrowOnError
  >,
): RequestResult<
  GetCartApiV1StorefrontTenantSlugCartsCartIdGetResponses,
  GetCartApiV1StorefrontTenantSlugCartsCartIdGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetCartApiV1StorefrontTenantSlugCartsCartIdGetResponses,
    GetCartApiV1StorefrontTenantSlugCartsCartIdGetErrors,
    ThrowOnError
  >({ url: "/api/v1/storefront/{tenant_slug}/carts/{cart_id}", ...options });

/**
 * Add Cart Item
 *
 * Add an item to an existing cart.
 */
export const addCartItemApiV1StorefrontTenantSlugCartsCartIdItemsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    AddCartItemApiV1StorefrontTenantSlugCartsCartIdItemsPostData,
    ThrowOnError
  >,
): RequestResult<
  AddCartItemApiV1StorefrontTenantSlugCartsCartIdItemsPostResponses,
  AddCartItemApiV1StorefrontTenantSlugCartsCartIdItemsPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AddCartItemApiV1StorefrontTenantSlugCartsCartIdItemsPostResponses,
    AddCartItemApiV1StorefrontTenantSlugCartsCartIdItemsPostErrors,
    ThrowOnError
  >({
    url: "/api/v1/storefront/{tenant_slug}/carts/{cart_id}/items",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Remove Cart Item
 *
 * Remove an item from the cart.
 */
export const removeCartItemApiV1StorefrontTenantSlugCartsCartIdItemsItemIdDelete =
  <ThrowOnError extends boolean = false>(
    options: Options<
      RemoveCartItemApiV1StorefrontTenantSlugCartsCartIdItemsItemIdDeleteData,
      ThrowOnError
    >,
  ): RequestResult<
    RemoveCartItemApiV1StorefrontTenantSlugCartsCartIdItemsItemIdDeleteResponses,
    RemoveCartItemApiV1StorefrontTenantSlugCartsCartIdItemsItemIdDeleteErrors,
    ThrowOnError
  > =>
    (options.client ?? client).delete<
      RemoveCartItemApiV1StorefrontTenantSlugCartsCartIdItemsItemIdDeleteResponses,
      RemoveCartItemApiV1StorefrontTenantSlugCartsCartIdItemsItemIdDeleteErrors,
      ThrowOnError
    >({
      url: "/api/v1/storefront/{tenant_slug}/carts/{cart_id}/items/{item_id}",
      ...options,
    });

/**
 * Update Cart Item
 *
 * Update item quantity. If quantity is 0, removes the item.
 */
export const updateCartItemApiV1StorefrontTenantSlugCartsCartIdItemsItemIdPatch =
  <ThrowOnError extends boolean = false>(
    options: Options<
      UpdateCartItemApiV1StorefrontTenantSlugCartsCartIdItemsItemIdPatchData,
      ThrowOnError
    >,
  ): RequestResult<
    UpdateCartItemApiV1StorefrontTenantSlugCartsCartIdItemsItemIdPatchResponses,
    UpdateCartItemApiV1StorefrontTenantSlugCartsCartIdItemsItemIdPatchErrors,
    ThrowOnError
  > =>
    (options.client ?? client).patch<
      UpdateCartItemApiV1StorefrontTenantSlugCartsCartIdItemsItemIdPatchResponses,
      UpdateCartItemApiV1StorefrontTenantSlugCartsCartIdItemsItemIdPatchErrors,
      ThrowOnError
    >({
      url: "/api/v1/storefront/{tenant_slug}/carts/{cart_id}/items/{item_id}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });

/**
 * Checkout
 *
 * Convert cart to order. Validates stock, creates order, decrements inventory.
 */
export const checkoutApiV1StorefrontTenantSlugCartsCartIdCheckoutPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    CheckoutApiV1StorefrontTenantSlugCartsCartIdCheckoutPostData,
    ThrowOnError
  >,
): RequestResult<
  CheckoutApiV1StorefrontTenantSlugCartsCartIdCheckoutPostResponses,
  CheckoutApiV1StorefrontTenantSlugCartsCartIdCheckoutPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CheckoutApiV1StorefrontTenantSlugCartsCartIdCheckoutPostResponses,
    CheckoutApiV1StorefrontTenantSlugCartsCartIdCheckoutPostErrors,
    ThrowOnError
  >({
    url: "/api/v1/storefront/{tenant_slug}/carts/{cart_id}/checkout",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Tenants
 */
export const listTenantsApiV1TenantsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListTenantsApiV1TenantsGetData, ThrowOnError>,
): RequestResult<ListTenantsApiV1TenantsGetResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    ListTenantsApiV1TenantsGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/v1/tenants/", ...options });

/**
 * Create Tenant
 */
export const createTenantApiV1TenantsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateTenantApiV1TenantsPostData, ThrowOnError>,
): RequestResult<
  CreateTenantApiV1TenantsPostResponses,
  CreateTenantApiV1TenantsPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateTenantApiV1TenantsPostResponses,
    CreateTenantApiV1TenantsPostErrors,
    ThrowOnError
  >({
    url: "/api/v1/tenants/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete Tenant
 */
export const deleteTenantApiV1TenantsTenantIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteTenantApiV1TenantsTenantIdDeleteData, ThrowOnError>,
): RequestResult<
  DeleteTenantApiV1TenantsTenantIdDeleteResponses,
  DeleteTenantApiV1TenantsTenantIdDeleteErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteTenantApiV1TenantsTenantIdDeleteResponses,
    DeleteTenantApiV1TenantsTenantIdDeleteErrors,
    ThrowOnError
  >({ url: "/api/v1/tenants/{tenant_id}", ...options });

/**
 * Get Tenant
 */
export const getTenantApiV1TenantsTenantIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetTenantApiV1TenantsTenantIdGetData, ThrowOnError>,
): RequestResult<
  GetTenantApiV1TenantsTenantIdGetResponses,
  GetTenantApiV1TenantsTenantIdGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetTenantApiV1TenantsTenantIdGetResponses,
    GetTenantApiV1TenantsTenantIdGetErrors,
    ThrowOnError
  >({ url: "/api/v1/tenants/{tenant_id}", ...options });

/**
 * Update Tenant
 */
export const updateTenantApiV1TenantsTenantIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateTenantApiV1TenantsTenantIdPutData, ThrowOnError>,
): RequestResult<
  UpdateTenantApiV1TenantsTenantIdPutResponses,
  UpdateTenantApiV1TenantsTenantIdPutErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateTenantApiV1TenantsTenantIdPutResponses,
    UpdateTenantApiV1TenantsTenantIdPutErrors,
    ThrowOnError
  >({
    url: "/api/v1/tenants/{tenant_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Products
 */
export const listProductsApiV1ProductsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListProductsApiV1ProductsGetData, ThrowOnError>,
): RequestResult<
  ListProductsApiV1ProductsGetResponses,
  ListProductsApiV1ProductsGetErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListProductsApiV1ProductsGetResponses,
    ListProductsApiV1ProductsGetErrors,
    ThrowOnError
  >({ url: "/api/v1/products/", ...options });

/**
 * Create Product
 */
export const createProductApiV1ProductsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateProductApiV1ProductsPostData, ThrowOnError>,
): RequestResult<
  CreateProductApiV1ProductsPostResponses,
  CreateProductApiV1ProductsPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateProductApiV1ProductsPostResponses,
    CreateProductApiV1ProductsPostErrors,
    ThrowOnError
  >({
    url: "/api/v1/products/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete Product
 */
export const deleteProductApiV1ProductsProductIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteProductApiV1ProductsProductIdDeleteData, ThrowOnError>,
): RequestResult<
  DeleteProductApiV1ProductsProductIdDeleteResponses,
  DeleteProductApiV1ProductsProductIdDeleteErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteProductApiV1ProductsProductIdDeleteResponses,
    DeleteProductApiV1ProductsProductIdDeleteErrors,
    ThrowOnError
  >({ url: "/api/v1/products/{product_id}", ...options });

/**
 * Get Product
 */
export const getProductApiV1ProductsProductIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetProductApiV1ProductsProductIdGetData, ThrowOnError>,
): RequestResult<
  GetProductApiV1ProductsProductIdGetResponses,
  GetProductApiV1ProductsProductIdGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetProductApiV1ProductsProductIdGetResponses,
    GetProductApiV1ProductsProductIdGetErrors,
    ThrowOnError
  >({ url: "/api/v1/products/{product_id}", ...options });

/**
 * Update Product
 */
export const updateProductApiV1ProductsProductIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateProductApiV1ProductsProductIdPutData, ThrowOnError>,
): RequestResult<
  UpdateProductApiV1ProductsProductIdPutResponses,
  UpdateProductApiV1ProductsProductIdPutErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateProductApiV1ProductsProductIdPutResponses,
    UpdateProductApiV1ProductsProductIdPutErrors,
    ThrowOnError
  >({
    url: "/api/v1/products/{product_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Variants
 */
export const listVariantsApiV1ProductsProductIdVariantsGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ListVariantsApiV1ProductsProductIdVariantsGetData,
    ThrowOnError
  >,
): RequestResult<
  ListVariantsApiV1ProductsProductIdVariantsGetResponses,
  ListVariantsApiV1ProductsProductIdVariantsGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListVariantsApiV1ProductsProductIdVariantsGetResponses,
    ListVariantsApiV1ProductsProductIdVariantsGetErrors,
    ThrowOnError
  >({ url: "/api/v1/products/{product_id}/variants", ...options });

/**
 * Create Variant
 */
export const createVariantApiV1ProductsProductIdVariantsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    CreateVariantApiV1ProductsProductIdVariantsPostData,
    ThrowOnError
  >,
): RequestResult<
  CreateVariantApiV1ProductsProductIdVariantsPostResponses,
  CreateVariantApiV1ProductsProductIdVariantsPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateVariantApiV1ProductsProductIdVariantsPostResponses,
    CreateVariantApiV1ProductsProductIdVariantsPostErrors,
    ThrowOnError
  >({
    url: "/api/v1/products/{product_id}/variants",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete Variant
 */
export const deleteVariantApiV1ProductsProductIdVariantsVariantIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteVariantApiV1ProductsProductIdVariantsVariantIdDeleteData,
    ThrowOnError
  >,
): RequestResult<
  DeleteVariantApiV1ProductsProductIdVariantsVariantIdDeleteResponses,
  DeleteVariantApiV1ProductsProductIdVariantsVariantIdDeleteErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteVariantApiV1ProductsProductIdVariantsVariantIdDeleteResponses,
    DeleteVariantApiV1ProductsProductIdVariantsVariantIdDeleteErrors,
    ThrowOnError
  >({ url: "/api/v1/products/{product_id}/variants/{variant_id}", ...options });

/**
 * Get Variant
 */
export const getVariantApiV1ProductsProductIdVariantsVariantIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetVariantApiV1ProductsProductIdVariantsVariantIdGetData,
    ThrowOnError
  >,
): RequestResult<
  GetVariantApiV1ProductsProductIdVariantsVariantIdGetResponses,
  GetVariantApiV1ProductsProductIdVariantsVariantIdGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetVariantApiV1ProductsProductIdVariantsVariantIdGetResponses,
    GetVariantApiV1ProductsProductIdVariantsVariantIdGetErrors,
    ThrowOnError
  >({ url: "/api/v1/products/{product_id}/variants/{variant_id}", ...options });

/**
 * Update Variant
 */
export const updateVariantApiV1ProductsProductIdVariantsVariantIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UpdateVariantApiV1ProductsProductIdVariantsVariantIdPutData,
    ThrowOnError
  >,
): RequestResult<
  UpdateVariantApiV1ProductsProductIdVariantsVariantIdPutResponses,
  UpdateVariantApiV1ProductsProductIdVariantsVariantIdPutErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateVariantApiV1ProductsProductIdVariantsVariantIdPutResponses,
    UpdateVariantApiV1ProductsProductIdVariantsVariantIdPutErrors,
    ThrowOnError
  >({
    url: "/api/v1/products/{product_id}/variants/{variant_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Orders
 */
export const listOrdersApiV1OrdersGet = <ThrowOnError extends boolean = false>(
  options?: Options<ListOrdersApiV1OrdersGetData, ThrowOnError>,
): RequestResult<
  ListOrdersApiV1OrdersGetResponses,
  ListOrdersApiV1OrdersGetErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListOrdersApiV1OrdersGetResponses,
    ListOrdersApiV1OrdersGetErrors,
    ThrowOnError
  >({ url: "/api/v1/orders/", ...options });

/**
 * Create Order
 */
export const createOrderApiV1OrdersPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateOrderApiV1OrdersPostData, ThrowOnError>,
): RequestResult<
  CreateOrderApiV1OrdersPostResponses,
  CreateOrderApiV1OrdersPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateOrderApiV1OrdersPostResponses,
    CreateOrderApiV1OrdersPostErrors,
    ThrowOnError
  >({
    url: "/api/v1/orders/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Order
 */
export const getOrderApiV1OrdersOrderIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetOrderApiV1OrdersOrderIdGetData, ThrowOnError>,
): RequestResult<
  GetOrderApiV1OrdersOrderIdGetResponses,
  GetOrderApiV1OrdersOrderIdGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetOrderApiV1OrdersOrderIdGetResponses,
    GetOrderApiV1OrdersOrderIdGetErrors,
    ThrowOnError
  >({ url: "/api/v1/orders/{order_id}", ...options });

/**
 * Patch Order
 */
export const patchOrderApiV1OrdersOrderIdPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PatchOrderApiV1OrdersOrderIdPatchData, ThrowOnError>,
): RequestResult<
  PatchOrderApiV1OrdersOrderIdPatchResponses,
  PatchOrderApiV1OrdersOrderIdPatchErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    PatchOrderApiV1OrdersOrderIdPatchResponses,
    PatchOrderApiV1OrdersOrderIdPatchErrors,
    ThrowOnError
  >({
    url: "/api/v1/orders/{order_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Update Order
 */
export const updateOrderApiV1OrdersOrderIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateOrderApiV1OrdersOrderIdPutData, ThrowOnError>,
): RequestResult<
  UpdateOrderApiV1OrdersOrderIdPutResponses,
  UpdateOrderApiV1OrdersOrderIdPutErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateOrderApiV1OrdersOrderIdPutResponses,
    UpdateOrderApiV1OrdersOrderIdPutErrors,
    ThrowOnError
  >({
    url: "/api/v1/orders/{order_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Order Purchase Orders
 *
 * Return all purchase orders linked to a given sales order.
 */
export const getOrderPurchaseOrdersApiV1OrdersOrderIdPurchaseOrdersGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetOrderPurchaseOrdersApiV1OrdersOrderIdPurchaseOrdersGetData,
    ThrowOnError
  >,
): RequestResult<
  GetOrderPurchaseOrdersApiV1OrdersOrderIdPurchaseOrdersGetResponses,
  GetOrderPurchaseOrdersApiV1OrdersOrderIdPurchaseOrdersGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetOrderPurchaseOrdersApiV1OrdersOrderIdPurchaseOrdersGetResponses,
    GetOrderPurchaseOrdersApiV1OrdersOrderIdPurchaseOrdersGetErrors,
    ThrowOnError
  >({ url: "/api/v1/orders/{order_id}/purchase-orders", ...options });

/**
 * Svix Webhook
 *
 * Handle Svix webhook relay with signature verification.
 */
export const svixWebhookWebhooksSvixPost = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<SvixWebhookWebhooksSvixPostData, ThrowOnError>,
): RequestResult<
  SvixWebhookWebhooksSvixPostResponses,
  SvixWebhookWebhooksSvixPostErrors,
  ThrowOnError
> =>
  (options?.client ?? client).post<
    SvixWebhookWebhooksSvixPostResponses,
    SvixWebhookWebhooksSvixPostErrors,
    ThrowOnError
  >({ url: "/webhooks/svix", ...options });

/**
 * Shopify Webhook
 *
 * Handle Shopify webhooks with HMAC verification.
 */
export const shopifyWebhookWebhooksShopifyPost = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ShopifyWebhookWebhooksShopifyPostData, ThrowOnError>,
): RequestResult<
  ShopifyWebhookWebhooksShopifyPostResponses,
  ShopifyWebhookWebhooksShopifyPostErrors,
  ThrowOnError
> =>
  (options?.client ?? client).post<
    ShopifyWebhookWebhooksShopifyPostResponses,
    ShopifyWebhookWebhooksShopifyPostErrors,
    ThrowOnError
  >({ url: "/webhooks/shopify", ...options });

/**
 * Register
 *
 * Register a new customer account.
 */
export const registerAuthRegisterPost = <ThrowOnError extends boolean = false>(
  options: Options<RegisterAuthRegisterPostData, ThrowOnError>,
): RequestResult<
  RegisterAuthRegisterPostResponses,
  RegisterAuthRegisterPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    RegisterAuthRegisterPostResponses,
    RegisterAuthRegisterPostErrors,
    ThrowOnError
  >({
    url: "/auth/register",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Login
 *
 * Authenticate and return JWT tokens.
 */
export const loginAuthLoginPost = <ThrowOnError extends boolean = false>(
  options: Options<LoginAuthLoginPostData, ThrowOnError>,
): RequestResult<
  LoginAuthLoginPostResponses,
  LoginAuthLoginPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    LoginAuthLoginPostResponses,
    LoginAuthLoginPostErrors,
    ThrowOnError
  >({
    url: "/auth/login",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Refresh Token
 *
 * Refresh an access token using a refresh token.
 */
export const refreshTokenAuthRefreshPost = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<RefreshTokenAuthRefreshPostData, ThrowOnError>,
): RequestResult<RefreshTokenAuthRefreshPostResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).post<
    RefreshTokenAuthRefreshPostResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/auth/refresh",
    ...options,
  });

/**
 * Logout
 *
 * Logout and blacklist the current token.
 */
export const logoutAuthLogoutPost = <ThrowOnError extends boolean = false>(
  options?: Options<LogoutAuthLogoutPostData, ThrowOnError>,
): RequestResult<LogoutAuthLogoutPostResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).post<
    LogoutAuthLogoutPostResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/auth/logout",
    ...options,
  });

/**
 * Register
 *
 * Register a new tenant admin user.
 */
export const registerAdminAuthRegisterPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<RegisterAdminAuthRegisterPostData, ThrowOnError>,
): RequestResult<
  RegisterAdminAuthRegisterPostResponses,
  RegisterAdminAuthRegisterPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    RegisterAdminAuthRegisterPostResponses,
    RegisterAdminAuthRegisterPostErrors,
    ThrowOnError
  >({
    url: "/admin/auth/register",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Login
 *
 * Authenticate tenant admin and return JWT tokens.
 */
export const loginAdminAuthLoginPost = <ThrowOnError extends boolean = false>(
  options: Options<LoginAdminAuthLoginPostData, ThrowOnError>,
): RequestResult<
  LoginAdminAuthLoginPostResponses,
  LoginAdminAuthLoginPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    LoginAdminAuthLoginPostResponses,
    LoginAdminAuthLoginPostErrors,
    ThrowOnError
  >({
    url: "/admin/auth/login",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Refresh
 *
 * Refresh an access token using a refresh token.
 */
export const refreshAdminAuthRefreshPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<RefreshAdminAuthRefreshPostData, ThrowOnError>,
): RequestResult<
  RefreshAdminAuthRefreshPostResponses,
  RefreshAdminAuthRefreshPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    RefreshAdminAuthRefreshPostResponses,
    RefreshAdminAuthRefreshPostErrors,
    ThrowOnError
  >({
    url: "/admin/auth/refresh",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Logout
 *
 * Logout and blacklist the current token.
 */
export const logoutAdminAuthLogoutPost = <ThrowOnError extends boolean = false>(
  options?: Options<LogoutAdminAuthLogoutPostData, ThrowOnError>,
): RequestResult<LogoutAdminAuthLogoutPostResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).post<
    LogoutAdminAuthLogoutPostResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/admin/auth/logout",
    ...options,
  });

/**
 * Me
 *
 * Get current admin user info.
 */
export const meAdminAuthMeGet = <ThrowOnError extends boolean = false>(
  options?: Options<MeAdminAuthMeGetData, ThrowOnError>,
): RequestResult<MeAdminAuthMeGetResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    MeAdminAuthMeGetResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/admin/auth/me",
    ...options,
  });

/**
 * Verify
 *
 * Verify admin token and return user info (alias for /me).
 */
export const verifyAdminAuthVerifyPost = <ThrowOnError extends boolean = false>(
  options?: Options<VerifyAdminAuthVerifyPostData, ThrowOnError>,
): RequestResult<VerifyAdminAuthVerifyPostResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).post<
    VerifyAdminAuthVerifyPostResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/admin/auth/verify",
    ...options,
  });

/**
 * Upload Signature
 *
 * Generate a signed upload signature for direct browser-to-Cloudinary uploads.
 *
 * Requires admin authentication. The frontend requests this before uploading,
 * so Cloudinary can verify the upload is authorized without exposing the
 * API secret to the client.
 */
export const uploadSignatureApiV1MediaUploadSignaturePost = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    UploadSignatureApiV1MediaUploadSignaturePostData,
    ThrowOnError
  >,
): RequestResult<
  UploadSignatureApiV1MediaUploadSignaturePostResponses,
  unknown,
  ThrowOnError
> =>
  (options?.client ?? client).post<
    UploadSignatureApiV1MediaUploadSignaturePostResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/v1/media/upload-signature", ...options });

/**
 * Create Product Image
 */
export const createProductImageApiV1ProductsProductIdImagesPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    CreateProductImageApiV1ProductsProductIdImagesPostData,
    ThrowOnError
  >,
): RequestResult<
  CreateProductImageApiV1ProductsProductIdImagesPostResponses,
  CreateProductImageApiV1ProductsProductIdImagesPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateProductImageApiV1ProductsProductIdImagesPostResponses,
    CreateProductImageApiV1ProductsProductIdImagesPostErrors,
    ThrowOnError
  >({
    url: "/api/v1/products/{product_id}/images",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete Product Image
 */
export const deleteProductImageApiV1ProductImagesImageIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteProductImageApiV1ProductImagesImageIdDeleteData,
    ThrowOnError
  >,
): RequestResult<
  DeleteProductImageApiV1ProductImagesImageIdDeleteResponses,
  DeleteProductImageApiV1ProductImagesImageIdDeleteErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteProductImageApiV1ProductImagesImageIdDeleteResponses,
    DeleteProductImageApiV1ProductImagesImageIdDeleteErrors,
    ThrowOnError
  >({ url: "/api/v1/product-images/{image_id}", ...options });

/**
 * Update Product Image
 */
export const updateProductImageApiV1ProductImagesImageIdPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UpdateProductImageApiV1ProductImagesImageIdPatchData,
    ThrowOnError
  >,
): RequestResult<
  UpdateProductImageApiV1ProductImagesImageIdPatchResponses,
  UpdateProductImageApiV1ProductImagesImageIdPatchErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    UpdateProductImageApiV1ProductImagesImageIdPatchResponses,
    UpdateProductImageApiV1ProductImagesImageIdPatchErrors,
    ThrowOnError
  >({
    url: "/api/v1/product-images/{image_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Categories
 */
export const listCategoriesApiV1CategoriesGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListCategoriesApiV1CategoriesGetData, ThrowOnError>,
): RequestResult<
  ListCategoriesApiV1CategoriesGetResponses,
  ListCategoriesApiV1CategoriesGetErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListCategoriesApiV1CategoriesGetResponses,
    ListCategoriesApiV1CategoriesGetErrors,
    ThrowOnError
  >({ url: "/api/v1/categories/", ...options });

/**
 * Create Category
 */
export const createCategoryApiV1CategoriesPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateCategoryApiV1CategoriesPostData, ThrowOnError>,
): RequestResult<
  CreateCategoryApiV1CategoriesPostResponses,
  CreateCategoryApiV1CategoriesPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateCategoryApiV1CategoriesPostResponses,
    CreateCategoryApiV1CategoriesPostErrors,
    ThrowOnError
  >({
    url: "/api/v1/categories/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete Category
 */
export const deleteCategoryApiV1CategoriesCategoryIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteCategoryApiV1CategoriesCategoryIdDeleteData,
    ThrowOnError
  >,
): RequestResult<
  DeleteCategoryApiV1CategoriesCategoryIdDeleteResponses,
  DeleteCategoryApiV1CategoriesCategoryIdDeleteErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteCategoryApiV1CategoriesCategoryIdDeleteResponses,
    DeleteCategoryApiV1CategoriesCategoryIdDeleteErrors,
    ThrowOnError
  >({ url: "/api/v1/categories/{category_id}", ...options });

/**
 * Update Category
 */
export const updateCategoryApiV1CategoriesCategoryIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UpdateCategoryApiV1CategoriesCategoryIdPutData,
    ThrowOnError
  >,
): RequestResult<
  UpdateCategoryApiV1CategoriesCategoryIdPutResponses,
  UpdateCategoryApiV1CategoriesCategoryIdPutErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateCategoryApiV1CategoriesCategoryIdPutResponses,
    UpdateCategoryApiV1CategoriesCategoryIdPutErrors,
    ThrowOnError
  >({
    url: "/api/v1/categories/{category_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Collections
 */
export const listCollectionsApiV1CollectionsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListCollectionsApiV1CollectionsGetData, ThrowOnError>,
): RequestResult<
  ListCollectionsApiV1CollectionsGetResponses,
  ListCollectionsApiV1CollectionsGetErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListCollectionsApiV1CollectionsGetResponses,
    ListCollectionsApiV1CollectionsGetErrors,
    ThrowOnError
  >({ url: "/api/v1/collections/", ...options });

/**
 * Create Collection
 */
export const createCollectionApiV1CollectionsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateCollectionApiV1CollectionsPostData, ThrowOnError>,
): RequestResult<
  CreateCollectionApiV1CollectionsPostResponses,
  CreateCollectionApiV1CollectionsPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateCollectionApiV1CollectionsPostResponses,
    CreateCollectionApiV1CollectionsPostErrors,
    ThrowOnError
  >({
    url: "/api/v1/collections/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete Collection
 */
export const deleteCollectionApiV1CollectionsCollectionIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteCollectionApiV1CollectionsCollectionIdDeleteData,
    ThrowOnError
  >,
): RequestResult<
  DeleteCollectionApiV1CollectionsCollectionIdDeleteResponses,
  DeleteCollectionApiV1CollectionsCollectionIdDeleteErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteCollectionApiV1CollectionsCollectionIdDeleteResponses,
    DeleteCollectionApiV1CollectionsCollectionIdDeleteErrors,
    ThrowOnError
  >({ url: "/api/v1/collections/{collection_id}", ...options });

/**
 * Update Collection
 */
export const updateCollectionApiV1CollectionsCollectionIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UpdateCollectionApiV1CollectionsCollectionIdPutData,
    ThrowOnError
  >,
): RequestResult<
  UpdateCollectionApiV1CollectionsCollectionIdPutResponses,
  UpdateCollectionApiV1CollectionsCollectionIdPutErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateCollectionApiV1CollectionsCollectionIdPutResponses,
    UpdateCollectionApiV1CollectionsCollectionIdPutErrors,
    ThrowOnError
  >({
    url: "/api/v1/collections/{collection_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Collection Products
 */
export const listCollectionProductsApiV1CollectionsCollectionIdProductsGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ListCollectionProductsApiV1CollectionsCollectionIdProductsGetData,
    ThrowOnError
  >,
): RequestResult<
  ListCollectionProductsApiV1CollectionsCollectionIdProductsGetResponses,
  ListCollectionProductsApiV1CollectionsCollectionIdProductsGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListCollectionProductsApiV1CollectionsCollectionIdProductsGetResponses,
    ListCollectionProductsApiV1CollectionsCollectionIdProductsGetErrors,
    ThrowOnError
  >({ url: "/api/v1/collections/{collection_id}/products", ...options });

/**
 * Add Products To Collection
 */
export const addProductsToCollectionApiV1CollectionsCollectionIdProductsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    AddProductsToCollectionApiV1CollectionsCollectionIdProductsPostData,
    ThrowOnError
  >,
): RequestResult<
  AddProductsToCollectionApiV1CollectionsCollectionIdProductsPostResponses,
  AddProductsToCollectionApiV1CollectionsCollectionIdProductsPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    AddProductsToCollectionApiV1CollectionsCollectionIdProductsPostResponses,
    AddProductsToCollectionApiV1CollectionsCollectionIdProductsPostErrors,
    ThrowOnError
  >({
    url: "/api/v1/collections/{collection_id}/products",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Remove Product From Collection
 */
export const removeProductFromCollectionApiV1CollectionsCollectionIdProductsProductIdDelete =
  <ThrowOnError extends boolean = false>(
    options: Options<
      RemoveProductFromCollectionApiV1CollectionsCollectionIdProductsProductIdDeleteData,
      ThrowOnError
    >,
  ): RequestResult<
    RemoveProductFromCollectionApiV1CollectionsCollectionIdProductsProductIdDeleteResponses,
    RemoveProductFromCollectionApiV1CollectionsCollectionIdProductsProductIdDeleteErrors,
    ThrowOnError
  > =>
    (options.client ?? client).delete<
      RemoveProductFromCollectionApiV1CollectionsCollectionIdProductsProductIdDeleteResponses,
      RemoveProductFromCollectionApiV1CollectionsCollectionIdProductsProductIdDeleteErrors,
      ThrowOnError
    >({
      url: "/api/v1/collections/{collection_id}/products/{product_id}",
      ...options,
    });

/**
 * List Customers
 */
export const listCustomersApiV1CustomersGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListCustomersApiV1CustomersGetData, ThrowOnError>,
): RequestResult<
  ListCustomersApiV1CustomersGetResponses,
  ListCustomersApiV1CustomersGetErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListCustomersApiV1CustomersGetResponses,
    ListCustomersApiV1CustomersGetErrors,
    ThrowOnError
  >({ url: "/api/v1/customers/", ...options });

/**
 * Get Customer
 */
export const getCustomerApiV1CustomersCustomerIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetCustomerApiV1CustomersCustomerIdGetData, ThrowOnError>,
): RequestResult<
  GetCustomerApiV1CustomersCustomerIdGetResponses,
  GetCustomerApiV1CustomersCustomerIdGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetCustomerApiV1CustomersCustomerIdGetResponses,
    GetCustomerApiV1CustomersCustomerIdGetErrors,
    ThrowOnError
  >({ url: "/api/v1/customers/{customer_id}", ...options });

/**
 * Dashboard Summary
 */
export const dashboardSummaryApiV1AdminDashboardSummaryGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    DashboardSummaryApiV1AdminDashboardSummaryGetData,
    ThrowOnError
  >,
): RequestResult<
  DashboardSummaryApiV1AdminDashboardSummaryGetResponses,
  DashboardSummaryApiV1AdminDashboardSummaryGetErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    DashboardSummaryApiV1AdminDashboardSummaryGetResponses,
    DashboardSummaryApiV1AdminDashboardSummaryGetErrors,
    ThrowOnError
  >({ url: "/api/v1/admin/dashboard/summary", ...options });

/**
 * Get Stats
 */
export const getStatsApiV1InventoryStatsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetStatsApiV1InventoryStatsGetData, ThrowOnError>,
): RequestResult<
  GetStatsApiV1InventoryStatsGetResponses,
  GetStatsApiV1InventoryStatsGetErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    GetStatsApiV1InventoryStatsGetResponses,
    GetStatsApiV1InventoryStatsGetErrors,
    ThrowOnError
  >({ url: "/api/v1/inventory/stats", ...options });

/**
 * List Items
 */
export const listItemsApiV1InventoryGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListItemsApiV1InventoryGetData, ThrowOnError>,
): RequestResult<
  ListItemsApiV1InventoryGetResponses,
  ListItemsApiV1InventoryGetErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListItemsApiV1InventoryGetResponses,
    ListItemsApiV1InventoryGetErrors,
    ThrowOnError
  >({ url: "/api/v1/inventory", ...options });

/**
 * Create Item
 */
export const createItemApiV1InventoryPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateItemApiV1InventoryPostData, ThrowOnError>,
): RequestResult<
  CreateItemApiV1InventoryPostResponses,
  CreateItemApiV1InventoryPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateItemApiV1InventoryPostResponses,
    CreateItemApiV1InventoryPostErrors,
    ThrowOnError
  >({
    url: "/api/v1/inventory",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete Item
 */
export const deleteItemApiV1InventoryItemIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteItemApiV1InventoryItemIdDeleteData, ThrowOnError>,
): RequestResult<
  DeleteItemApiV1InventoryItemIdDeleteResponses,
  DeleteItemApiV1InventoryItemIdDeleteErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteItemApiV1InventoryItemIdDeleteResponses,
    DeleteItemApiV1InventoryItemIdDeleteErrors,
    ThrowOnError
  >({ url: "/api/v1/inventory/{item_id}", ...options });

/**
 * Get Item
 */
export const getItemApiV1InventoryItemIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetItemApiV1InventoryItemIdGetData, ThrowOnError>,
): RequestResult<
  GetItemApiV1InventoryItemIdGetResponses,
  GetItemApiV1InventoryItemIdGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetItemApiV1InventoryItemIdGetResponses,
    GetItemApiV1InventoryItemIdGetErrors,
    ThrowOnError
  >({ url: "/api/v1/inventory/{item_id}", ...options });

/**
 * Update Item
 */
export const updateItemApiV1InventoryItemIdPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateItemApiV1InventoryItemIdPatchData, ThrowOnError>,
): RequestResult<
  UpdateItemApiV1InventoryItemIdPatchResponses,
  UpdateItemApiV1InventoryItemIdPatchErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    UpdateItemApiV1InventoryItemIdPatchResponses,
    UpdateItemApiV1InventoryItemIdPatchErrors,
    ThrowOnError
  >({
    url: "/api/v1/inventory/{item_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Suppliers
 */
export const listSuppliersApiV1SuppliersGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListSuppliersApiV1SuppliersGetData, ThrowOnError>,
): RequestResult<
  ListSuppliersApiV1SuppliersGetResponses,
  ListSuppliersApiV1SuppliersGetErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListSuppliersApiV1SuppliersGetResponses,
    ListSuppliersApiV1SuppliersGetErrors,
    ThrowOnError
  >({ url: "/api/v1/suppliers", ...options });

/**
 * Create Supplier
 */
export const createSupplierApiV1SuppliersPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateSupplierApiV1SuppliersPostData, ThrowOnError>,
): RequestResult<
  CreateSupplierApiV1SuppliersPostResponses,
  CreateSupplierApiV1SuppliersPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateSupplierApiV1SuppliersPostResponses,
    CreateSupplierApiV1SuppliersPostErrors,
    ThrowOnError
  >({
    url: "/api/v1/suppliers",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete Supplier
 */
export const deleteSupplierApiV1SuppliersSupplierIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteSupplierApiV1SuppliersSupplierIdDeleteData,
    ThrowOnError
  >,
): RequestResult<
  DeleteSupplierApiV1SuppliersSupplierIdDeleteResponses,
  DeleteSupplierApiV1SuppliersSupplierIdDeleteErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteSupplierApiV1SuppliersSupplierIdDeleteResponses,
    DeleteSupplierApiV1SuppliersSupplierIdDeleteErrors,
    ThrowOnError
  >({ url: "/api/v1/suppliers/{supplier_id}", ...options });

/**
 * Get Supplier
 */
export const getSupplierApiV1SuppliersSupplierIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetSupplierApiV1SuppliersSupplierIdGetData, ThrowOnError>,
): RequestResult<
  GetSupplierApiV1SuppliersSupplierIdGetResponses,
  GetSupplierApiV1SuppliersSupplierIdGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetSupplierApiV1SuppliersSupplierIdGetResponses,
    GetSupplierApiV1SuppliersSupplierIdGetErrors,
    ThrowOnError
  >({ url: "/api/v1/suppliers/{supplier_id}", ...options });

/**
 * Update Supplier
 */
export const updateSupplierApiV1SuppliersSupplierIdPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UpdateSupplierApiV1SuppliersSupplierIdPatchData,
    ThrowOnError
  >,
): RequestResult<
  UpdateSupplierApiV1SuppliersSupplierIdPatchResponses,
  UpdateSupplierApiV1SuppliersSupplierIdPatchErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    UpdateSupplierApiV1SuppliersSupplierIdPatchResponses,
    UpdateSupplierApiV1SuppliersSupplierIdPatchErrors,
    ThrowOnError
  >({
    url: "/api/v1/suppliers/{supplier_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List Purchase Orders
 */
export const listPurchaseOrdersApiV1PurchaseOrdersGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListPurchaseOrdersApiV1PurchaseOrdersGetData, ThrowOnError>,
): RequestResult<
  ListPurchaseOrdersApiV1PurchaseOrdersGetResponses,
  ListPurchaseOrdersApiV1PurchaseOrdersGetErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListPurchaseOrdersApiV1PurchaseOrdersGetResponses,
    ListPurchaseOrdersApiV1PurchaseOrdersGetErrors,
    ThrowOnError
  >({ url: "/api/v1/purchase-orders", ...options });

/**
 * List Pending Orders
 */
export const listPendingOrdersApiV1PurchaseOrdersPendingGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    ListPendingOrdersApiV1PurchaseOrdersPendingGetData,
    ThrowOnError
  >,
): RequestResult<
  ListPendingOrdersApiV1PurchaseOrdersPendingGetResponses,
  ListPendingOrdersApiV1PurchaseOrdersPendingGetErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListPendingOrdersApiV1PurchaseOrdersPendingGetResponses,
    ListPendingOrdersApiV1PurchaseOrdersPendingGetErrors,
    ThrowOnError
  >({ url: "/api/v1/purchase-orders/pending", ...options });

/**
 * Get Purchase Order
 */
export const getPurchaseOrderApiV1PurchaseOrdersPoIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetPurchaseOrderApiV1PurchaseOrdersPoIdGetData,
    ThrowOnError
  >,
): RequestResult<
  GetPurchaseOrderApiV1PurchaseOrdersPoIdGetResponses,
  GetPurchaseOrderApiV1PurchaseOrdersPoIdGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetPurchaseOrderApiV1PurchaseOrdersPoIdGetResponses,
    GetPurchaseOrderApiV1PurchaseOrdersPoIdGetErrors,
    ThrowOnError
  >({ url: "/api/v1/purchase-orders/{po_id}", ...options });

/**
 * Update Purchase Order
 */
export const updatePurchaseOrderApiV1PurchaseOrdersPoIdPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UpdatePurchaseOrderApiV1PurchaseOrdersPoIdPatchData,
    ThrowOnError
  >,
): RequestResult<
  UpdatePurchaseOrderApiV1PurchaseOrdersPoIdPatchResponses,
  UpdatePurchaseOrderApiV1PurchaseOrdersPoIdPatchErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    UpdatePurchaseOrderApiV1PurchaseOrdersPoIdPatchResponses,
    UpdatePurchaseOrderApiV1PurchaseOrdersPoIdPatchErrors,
    ThrowOnError
  >({
    url: "/api/v1/purchase-orders/{po_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Approve Purchase Order
 */
export const approvePurchaseOrderApiV1PurchaseOrdersPoIdApprovePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ApprovePurchaseOrderApiV1PurchaseOrdersPoIdApprovePostData,
    ThrowOnError
  >,
): RequestResult<
  ApprovePurchaseOrderApiV1PurchaseOrdersPoIdApprovePostResponses,
  ApprovePurchaseOrderApiV1PurchaseOrdersPoIdApprovePostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    ApprovePurchaseOrderApiV1PurchaseOrdersPoIdApprovePostResponses,
    ApprovePurchaseOrderApiV1PurchaseOrdersPoIdApprovePostErrors,
    ThrowOnError
  >({ url: "/api/v1/purchase-orders/{po_id}/approve", ...options });

/**
 * Cancel Purchase Order
 */
export const cancelPurchaseOrderApiV1PurchaseOrdersPoIdCancelPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    CancelPurchaseOrderApiV1PurchaseOrdersPoIdCancelPostData,
    ThrowOnError
  >,
): RequestResult<
  CancelPurchaseOrderApiV1PurchaseOrdersPoIdCancelPostResponses,
  CancelPurchaseOrderApiV1PurchaseOrdersPoIdCancelPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CancelPurchaseOrderApiV1PurchaseOrdersPoIdCancelPostResponses,
    CancelPurchaseOrderApiV1PurchaseOrdersPoIdCancelPostErrors,
    ThrowOnError
  >({ url: "/api/v1/purchase-orders/{po_id}/cancel", ...options });

/**
 * Health
 */
export const healthHealthGet = <ThrowOnError extends boolean = false>(
  options?: Options<HealthHealthGetData, ThrowOnError>,
): RequestResult<HealthHealthGetResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    HealthHealthGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/health", ...options });
