// This file is auto-generated by @hey-api/openapi-ts

import { z } from "zod";

/**
 * AddressSnapshot
 */
export const zAddressSnapshot = z.object({
  line1: z.string().nullish(),
  line2: z.string().nullish(),
  city: z.string().nullish(),
  province: z.string().nullish(),
  postal_code: z.string().nullish(),
  country: z.string().nullish(),
});

/**
 * AdminLoginRequest
 */
export const zAdminLoginRequest = z.object({
  email: z.string(),
  password: z.string(),
});

/**
 * AdminRefreshRequest
 */
export const zAdminRefreshRequest = z.object({
  refresh_token: z.string(),
});

/**
 * AdminRegisterRequest
 */
export const zAdminRegisterRequest = z.object({
  email: z.string(),
  password: z.string().min(8),
  first_name: z.string().max(100),
  last_name: z.string().max(100),
  tenant_slug: z.string(),
});

/**
 * AdminTokenResponse
 */
export const zAdminTokenResponse = z.object({
  access_token: z.string(),
  refresh_token: z.string(),
  token_type: z.string().optional().default("bearer"),
});

/**
 * AdminUserResponse
 */
export const zAdminUserResponse = z.object({
  user_id: z.string().uuid(),
  email: z.string(),
  tenant_id: z.string().uuid(),
  role: z.string(),
  is_active: z.boolean(),
});

/**
 * AssociatedPOResponse
 */
export const zAssociatedPoResponse = z.object({
  id: z.string().uuid(),
  po_number: z.string(),
  status: z.string(),
  supplier_name: z.string(),
  total: z.number().int(),
  fulfillment_strategy: z.string(),
  created_at: z.string().datetime(),
});

/**
 * CartAddItemRequest
 */
export const zCartAddItemRequest = z.object({
  variant_id: z.string().uuid(),
  quantity: z.number().int().gte(1).optional().default(1),
});

/**
 * CartItemResponse
 */
export const zCartItemResponse = z.object({
  id: z.string().uuid(),
  variant_id: z.string().uuid(),
  sku: z.string().optional().default(""),
  product_name: z.string().optional().default(""),
  variant_name: z.string().nullish(),
  price: z.number().int().gte(0),
  quantity: z.number().int().gte(1),
  image_url: z.string().nullish(),
});

/**
 * CartResponse
 */
export const zCartResponse = z.object({
  id: z.string().uuid(),
  items: z.array(zCartItemResponse).optional().default([]),
  item_count: z.number().int().optional().default(0),
  total: z.number().int().gte(0),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
});

/**
 * CartUpdateItemRequest
 */
export const zCartUpdateItemRequest = z.object({
  quantity: z.number().int().gte(0),
});

/**
 * CategoryCreate
 */
export const zCategoryCreate = z.object({
  name: z.string().max(255),
  slug: z.string().max(255),
  description: z.string().nullish(),
  image_url: z.string().nullish(),
  sort_order: z.number().int().optional().default(0),
});

/**
 * CategoryResponse
 */
export const zCategoryResponse = z.object({
  id: z.string().uuid(),
  tenant_id: z.string().uuid(),
  name: z.string(),
  slug: z.string(),
  description: z.string().nullish(),
  image_url: z.string().nullish(),
  sort_order: z.number().int(),
  is_active: z.boolean(),
  product_count: z.number().int().optional().default(0),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
});

/**
 * CategoryUpdate
 */
export const zCategoryUpdate = z.object({
  name: z.string().max(255).nullish(),
  slug: z.string().max(255).nullish(),
  description: z.string().nullish(),
  image_url: z.string().nullish(),
  sort_order: z.number().int().nullish(),
  is_active: z.boolean().nullish(),
});

/**
 * CheckoutRequest
 */
export const zCheckoutRequest = z.object({
  currency: z.string().optional().default("USD"),
  shipping_address: z.record(z.unknown()).optional(),
  billing_address: z.record(z.unknown()).optional(),
  notes: z.string().nullish(),
});

/**
 * CollectionCreate
 */
export const zCollectionCreate = z.object({
  name: z.string().min(1).max(255),
  slug: z.string().min(1).max(255),
  description: z.string().nullish(),
  hero_image_url: z.string().max(2048).nullish(),
  hero_image_alt: z.string().max(500).nullish(),
  sort_order: z.number().int().optional().default(0),
  is_active: z.boolean().optional().default(true),
});

/**
 * CollectionResponse
 */
export const zCollectionResponse = z.object({
  id: z.string().uuid(),
  tenant_id: z.string().uuid(),
  name: z.string(),
  slug: z.string(),
  description: z.string().nullish(),
  hero_image_url: z.string().nullish(),
  hero_image_alt: z.string().nullish(),
  sort_order: z.number().int(),
  is_active: z.boolean(),
  product_count: z.number().int().optional().default(0),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
});

/**
 * CollectionUpdate
 */
export const zCollectionUpdate = z.object({
  name: z.string().min(1).max(255).nullish(),
  slug: z.string().min(1).max(255).nullish(),
  description: z.string().nullish(),
  hero_image_url: z.string().max(2048).nullish(),
  hero_image_alt: z.string().max(500).nullish(),
  sort_order: z.number().int().nullish(),
  is_active: z.boolean().nullish(),
});

/**
 * CustomerAddressResponse
 */
export const zCustomerAddressResponse = z.object({
  id: z.string().uuid(),
  address_type: z.string(),
  line1: z.string(),
  line2: z.string().nullish(),
  city: z.string(),
  province: z.string().nullish(),
  postal_code: z.string(),
  country: z.string(),
  is_default: z.boolean(),
});

/**
 * CustomerOrderResponse
 */
export const zCustomerOrderResponse = z.object({
  id: z.string().uuid(),
  order_number: z.string(),
  total: z.number().int(),
  status: z.string(),
  created_at: z.string().datetime(),
});

/**
 * CustomerDetailResponse
 */
export const zCustomerDetailResponse = z.object({
  id: z.string().uuid(),
  tenant_id: z.string().uuid(),
  email: z.string(),
  first_name: z.string().nullish(),
  last_name: z.string().nullish(),
  phone: z.string().nullish(),
  is_verified: z.boolean(),
  total_orders: z.number().int(),
  total_spent: z.number().int(),
  last_order_at: z.string().datetime().nullish(),
  average_order_value: z.number().int().optional().default(0),
  addresses: z.array(zCustomerAddressResponse).optional().default([]),
  orders: z.array(zCustomerOrderResponse).optional().default([]),
});

/**
 * FulfillmentCounts
 */
export const zFulfillmentCounts = z.object({
  unfulfilled: z.number().int().optional().default(0),
  processing: z.number().int().optional().default(0),
  shipped: z.number().int().optional().default(0),
  delivered: z.number().int().optional().default(0),
});

/**
 * InventoryItemCreateInput
 */
export const zInventoryItemCreateInput = z.object({
  name: z.string().min(1),
  sku: z.string().min(1),
  category: z.string().nullish(),
  supplier: z.string().nullish(),
  price: z.number().int().gte(0).nullish(),
  stock: z.number().int().gte(0).nullish().default(0),
});

/**
 * InventoryItemPatchInput
 */
export const zInventoryItemPatchInput = z.object({
  name: z.string().nullish(),
  sku: z.string().nullish(),
  category: z.string().nullish(),
  supplier: z.string().nullish(),
  price: z.number().int().gte(0).nullish(),
  stock: z.number().int().gte(0).nullish(),
});

/**
 * InventoryStatsResponse
 */
export const zInventoryStatsResponse = z.object({
  total_skus: z.number().int(),
  total_value: z.number().int(),
  low_stock_count: z.number().int(),
  out_of_stock_count: z.number().int(),
  total_variants: z.number().int(),
});

/**
 * InventoryVariantResponse
 */
export const zInventoryVariantResponse = z.object({
  id: z.string().uuid(),
  item_id: z.string().uuid(),
  name: z.string(),
  sku: z.string(),
  barcode: z.string().nullish(),
  price: z.number().int().gte(0),
  cost: z.number().int().gte(0),
  stock: z.number().int(),
  reorder_point: z.number().int().optional().default(0),
  warehouse: z.string().optional().default("Default"),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
});

/**
 * InventoryItemResponse
 */
export const zInventoryItemResponse = z.object({
  id: z.string().uuid(),
  tenant_id: z.string().uuid(),
  sku: z.string(),
  name: z.string(),
  description: z.string().nullish(),
  category: z.string().nullish(),
  image_url: z.string().nullish(),
  status: z.string(),
  supplier: z.string().nullish(),
  total_stock: z.number().int(),
  total_value: z.number().int(),
  variants: z.array(zInventoryVariantResponse),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
});

/**
 * LoginRequest
 */
export const zLoginRequest = z.object({
  email: z.string().email(),
  password: z.string(),
});

/**
 * LoginResponse
 */
export const zLoginResponse = z.object({
  access_token: z.string(),
  refresh_token: z.string(),
  token_type: z.string().optional().default("bearer"),
});

/**
 * LowStockItem
 */
export const zLowStockItem = z.object({
  variant_id: z.string().uuid(),
  product_name: z.string(),
  sku: z.string(),
  quantity: z.number().int(),
  threshold: z.number().int().optional().default(5),
});

/**
 * OrderItemCreate
 */
export const zOrderItemCreate = z.object({
  variant_id: z.string().uuid().nullish(),
  product_id: z.string().uuid().nullish(),
  product_name: z.string().optional().default(""),
  sku: z.string().optional().default(""),
  quantity: z.number().int().gte(1),
  unit_price: z.number().int().gte(0),
  total_price: z.number().int().gte(0).optional().default(0),
  discount: z.number().int().gte(0).optional().default(0),
});

/**
 * OrderCreate
 */
export const zOrderCreate = z.object({
  customer_id: z.string().uuid().nullish(),
  order_number: z.string().nullish(),
  status: z.string().nullish(),
  items: z.array(zOrderItemCreate),
  subtotal: z.number().int().gte(0).optional().default(0),
  total: z.number().int().gte(0).optional().default(0),
  shipping_address: z.record(z.unknown()).optional(),
  billing_address: z.record(z.unknown()).optional(),
  notes: z.string().nullish(),
  currency: z.string().optional().default("USD"),
});

/**
 * OrderItemResponse
 */
export const zOrderItemResponse = z.object({
  id: z.string().uuid(),
  order_id: z.string().uuid(),
  variant_id: z.string().uuid().nullish(),
  product_id: z.string().uuid().nullish(),
  product_name: z.string(),
  variant_name: z.string().nullish(),
  sku: z.string(),
  quantity: z.number().int(),
  unit_price: z.number().int(),
  total_price: z.number().int(),
  discount: z.number().int(),
  created_at: z.string().datetime(),
});

/**
 * OrderResponse
 */
export const zOrderResponse = z.object({
  id: z.string().uuid(),
  tenant_id: z.string().uuid(),
  customer_id: z.string().uuid().nullish(),
  order_number: z.string(),
  status: z.string(),
  payment_status: z.string(),
  payment_method: z.string().nullish(),
  payment_intent_id: z.string().nullish(),
  subtotal: z.number().int(),
  tax: z.number().int(),
  shipping: z.number().int(),
  discount: z.number().int(),
  total: z.number().int(),
  currency: z.string(),
  shipping_address: z.record(z.unknown()),
  billing_address: z.record(z.unknown()),
  notes: z.string().nullish(),
  customer_email: z.string().nullish(),
  options: z.record(z.unknown()).nullish(),
  items: z.array(zOrderItemResponse),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
});

/**
 * OrderUpdate
 */
export const zOrderUpdate = z.object({
  status: z.string().nullish(),
  payment_status: z.string().nullish(),
  shipping_address: z.record(z.unknown()).nullish(),
  billing_address: z.record(z.unknown()).nullish(),
  notes: z.string().nullish(),
});

/**
 * PaginationMeta
 */
export const zPaginationMeta = z.object({
  page: z.number().int(),
  page_size: z.number().int(),
  total: z.number().int(),
  total_pages: z.number().int(),
});

/**
 * PaginatedResponse[InventoryItemResponse]
 */
export const zPaginatedResponseInventoryItemResponse = z.object({
  data: z.array(zInventoryItemResponse),
  pagination: zPaginationMeta,
});

/**
 * PendingPOStats
 */
export const zPendingPoStats = z.object({
  count: z.number().int().optional().default(0),
  total: z.number().int().optional().default(0),
});

/**
 * ProductCreate
 */
export const zProductCreate = z.object({
  name: z.string().min(1).max(255),
  slug: z.string().min(1).max(255),
  description: z.string().nullish(),
  status: z.string().optional().default("draft"),
  sku: z.string().nullish(),
  weight: z.number().nullish(),
  weight_unit: z.string().optional().default("kg"),
  is_active: z.boolean().optional().default(true),
});

/**
 * ProductImageCreate
 */
export const zProductImageCreate = z.object({
  url: z.string().min(1).max(2048),
  alt_text: z.string().max(500).nullish(),
  sort_order: z.number().int().optional().default(0),
});

/**
 * ProductImageResponse
 */
export const zProductImageResponse = z.object({
  id: z.string().uuid(),
  url: z.string(),
  alt_text: z.string().nullish(),
  sort_order: z.number().int(),
});

/**
 * ProductImageUpdate
 */
export const zProductImageUpdate = z.object({
  alt_text: z.string().max(500).nullish(),
  sort_order: z.number().int().nullish(),
});

/**
 * ProductResponse
 */
export const zProductResponse = z.object({
  id: z.string().uuid(),
  tenant_id: z.string().uuid(),
  name: z.string(),
  slug: z.string(),
  description: z.string().nullish(),
  status: z.string(),
  sku: z.string().nullish(),
  weight: z.number().nullish(),
  weight_unit: z.string(),
  is_active: z.boolean(),
  images: z.array(zProductImageResponse).optional().default([]),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
});

/**
 * ProductUpdate
 */
export const zProductUpdate = z.object({
  name: z.string().min(1).max(255).nullish(),
  slug: z.string().min(1).max(255).nullish(),
  description: z.string().nullish(),
  status: z.string().nullish(),
  sku: z.string().nullish(),
  weight: z.number().nullish(),
  weight_unit: z.string().nullish(),
  is_active: z.boolean().nullish(),
});

/**
 * PurchaseOrderItemResponse
 */
export const zPurchaseOrderItemResponse = z.object({
  id: z.string().uuid(),
  variant_id: z.string().uuid(),
  supplier_sku: z.string().nullish(),
  product_name: z.string(),
  variant_label: z.string(),
  quantity: z.number().int(),
  unit_cost: z.number().int(),
  subtotal: z.number().int(),
  received_quantity: z.number().int().nullish(),
});

/**
 * PurchaseOrderPatchInput
 */
export const zPurchaseOrderPatchInput = z.object({
  status: z.string().nullish(),
  tracking_number: z.string().nullish(),
  carrier: z.string().nullish(),
  notes: z.string().nullish(),
});

/**
 * PurchaseOrderResponse
 */
export const zPurchaseOrderResponse = z.object({
  id: z.string().uuid(),
  tenant_id: z.string().uuid(),
  po_number: z.string(),
  supplier_id: z.string().uuid(),
  supplier_name: z.string(),
  status: z.string(),
  fulfillment_strategy: z.string(),
  ship_to_address: zAddressSnapshot.nullish(),
  tracking_number: z.string().nullish(),
  carrier: z.string().nullish(),
  subtotal: z.number().int(),
  tax: z.number().int(),
  shipping_cost: z.number().int(),
  total: z.number().int(),
  source_order_number: z.string().nullish(),
  items: z.array(zPurchaseOrderItemResponse),
  notes: z.string().nullish(),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
  sent_at: z.string().datetime().nullish(),
  confirmed_at: z.string().datetime().nullish(),
  closed_at: z.string().datetime().nullish(),
});

/**
 * PurchaseOrderListResponse
 */
export const zPurchaseOrderListResponse = z.object({
  data: z.array(zPurchaseOrderResponse),
  pagination: zPaginationMeta,
});

/**
 * RecentOrderItem
 */
export const zRecentOrderItem = z.object({
  id: z.string().uuid(),
  order_number: z.string(),
  customer_name: z.string().nullish(),
  total: z.number().int(),
  status: z.string(),
  created_at: z.string(),
});

/**
 * DashboardSummaryResponse
 */
export const zDashboardSummaryResponse = z.object({
  revenue_mtd: z.number().int().optional().default(0),
  revenue_total: z.number().int().optional().default(0),
  revenue_prev_mtd: z.number().int().optional().default(0),
  orders_mtd: z.number().int().optional().default(0),
  orders_total: z.number().int().optional().default(0),
  orders_prev_mtd: z.number().int().optional().default(0),
  aov: z.number().int().optional().default(0),
  active_customers: z.number().int().optional().default(0),
  active_customers_prev: z.number().int().optional().default(0),
  fulfillment: zFulfillmentCounts.optional().default({
    unfulfilled: 0,
    processing: 0,
    shipped: 0,
    delivered: 0,
  }),
  low_stock: z.array(zLowStockItem).optional().default([]),
  recent_orders: z.array(zRecentOrderItem).optional().default([]),
  pending_pos: zPendingPoStats.optional().default({ count: 0, total: 0 }),
});

/**
 * RegisterRequest
 */
export const zRegisterRequest = z.object({
  email: z.string().email(),
  password: z.string().min(8),
  first_name: z.string().max(100),
  last_name: z.string().max(100),
});

/**
 * RegisterResponse
 */
export const zRegisterResponse = z.object({
  user_id: z.string().uuid(),
  email: z.string(),
  tenant_id: z.string().uuid(),
});

/**
 * StorefrontImageResponse
 */
export const zStorefrontImageResponse = z.object({
  id: z.string().uuid(),
  url: z.string(),
  alt_text: z.string().nullish(),
  sort_order: z.number().int(),
});

/**
 * StorefrontVariantResponse
 */
export const zStorefrontVariantResponse = z.object({
  id: z.string().uuid(),
  sku: z.string(),
  price: z.number().int().gte(0),
  compare_at_price: z.number().int().gte(0).nullish(),
  is_active: z.boolean(),
  in_stock: z.boolean(),
  options: z.record(z.unknown()),
});

/**
 * StorefrontProductResponse
 */
export const zStorefrontProductResponse = z.object({
  id: z.string().uuid(),
  slug: z.string(),
  name: z.string(),
  description: z.string().nullish(),
  status: z.string(),
  min_price: z.number().int().gte(0),
  max_price: z.number().int().gte(0),
  images: z.array(zStorefrontImageResponse).optional().default([]),
  variants: z.array(zStorefrontVariantResponse).optional().default([]),
  category_slug: z.string().nullish(),
  collection_slugs: z.array(z.string()).optional().default([]),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
});

/**
 * PaginatedResponse[StorefrontProductResponse]
 */
export const zPaginatedResponseStorefrontProductResponse = z.object({
  data: z.array(zStorefrontProductResponse),
  pagination: zPaginationMeta,
});

/**
 * SupplierCreateInput
 */
export const zSupplierCreateInput = z.object({
  name: z.string().min(1).max(255),
  contact_email: z.string().max(255).nullish(),
  contact_phone: z.string().max(50).nullish(),
  delivery_method: z.string().optional().default("manual_email"),
});

/**
 * SupplierPatchInput
 */
export const zSupplierPatchInput = z.object({
  name: z.string().min(1).max(255).nullish(),
  contact_email: z.string().max(255).nullish(),
  contact_phone: z.string().max(50).nullish(),
  delivery_method: z.string().nullish(),
});

/**
 * SupplierResponse
 */
export const zSupplierResponse = z.object({
  id: z.string().uuid(),
  tenant_id: z.string().uuid(),
  name: z.string(),
  contact_email: z.string().nullish(),
  contact_phone: z.string().nullish(),
  delivery_method: z.string(),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
});

/**
 * SupplierListResponse
 */
export const zSupplierListResponse = z.object({
  data: z.array(zSupplierResponse),
  pagination: zPaginationMeta,
});

/**
 * TenantCreate
 */
export const zTenantCreate = z.object({
  name: z.string(),
  slug: z.string(),
});

/**
 * TenantPublicResponse
 */
export const zTenantPublicResponse = z.object({
  id: z.string().uuid(),
  tenant_id: z.string().uuid(),
  name: z.string(),
  slug: z.string(),
});

/**
 * TenantResponse
 */
export const zTenantResponse = z.object({
  id: z.string().uuid(),
  tenant_id: z.string().uuid(),
  name: z.string(),
  slug: z.string(),
  status: z.string(),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
});

/**
 * TenantSettingsResponse
 */
export const zTenantSettingsResponse = z.object({
  name: z.string(),
  slug: z.string(),
  currency: z.string().optional().default("USD"),
  theme: z.record(z.unknown()).optional().default({}),
});

/**
 * TenantUpdate
 */
export const zTenantUpdate = z.object({
  name: z.string().nullish(),
  slug: z.string().nullish(),
  status: z.string().nullish(),
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
  loc: z.array(z.union([z.string(), z.number().int()])),
  msg: z.string(),
  type: z.string(),
  input: z.unknown().optional(),
  ctx: z.record(z.unknown()).optional(),
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
  detail: z.array(zValidationError).optional(),
});

/**
 * VariantCreate
 */
export const zVariantCreate = z.object({
  sku: z.string().min(1).max(100),
  barcode: z.string().nullish(),
  price: z.number().int().gte(0),
  compare_at_price: z.number().int().gte(0).nullish(),
  weight: z.number().nullish(),
  weight_unit: z.string().optional().default("kg"),
  inventory_quantity: z.number().int().gte(0).optional().default(0),
  is_active: z.boolean().optional().default(true),
  options: z.record(z.unknown()).optional(),
});

/**
 * VariantResponse
 */
export const zVariantResponse = z.object({
  id: z.string().uuid(),
  product_id: z.string().uuid(),
  sku: z.string(),
  barcode: z.string().nullish(),
  price: z.number().int().gte(0),
  compare_at_price: z.number().int().gte(0).nullish(),
  weight: z.number().nullish(),
  weight_unit: z.string(),
  inventory_quantity: z.number().int(),
  is_active: z.boolean(),
  options: z.record(z.unknown()),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime(),
});

/**
 * VariantUpdate
 */
export const zVariantUpdate = z.object({
  sku: z.string().min(1).max(100).nullish(),
  barcode: z.string().nullish(),
  price: z.number().int().gte(0).nullish(),
  compare_at_price: z.number().int().gte(0).nullish(),
  weight: z.number().nullish(),
  weight_unit: z.string().nullish(),
  inventory_quantity: z.number().int().gte(0).nullish(),
  is_active: z.boolean().nullish(),
  options: z.record(z.unknown()).nullish(),
});

export const zResolveTenantApiV1PublicTenantsSlugGetPath = z.object({
  slug: z.string(),
});

/**
 * Successful Response
 */
export const zResolveTenantApiV1PublicTenantsSlugGetResponse =
  zTenantPublicResponse;

export const zPublicProductsApiV1PublicProductsTenantSlugGetPath = z.object({
  tenant_slug: z.string(),
});

export const zPublicProductsApiV1PublicProductsTenantSlugGetQuery = z.object({
  category: z.string().nullish(),
});

/**
 * Response Public Products Api V1 Public Products  Tenant Slug  Get
 *
 * Successful Response
 */
export const zPublicProductsApiV1PublicProductsTenantSlugGetResponse =
  z.array(zProductResponse);

export const zPublicCategoriesApiV1PublicCategoriesTenantSlugGetPath = z.object(
  {
    tenant_slug: z.string(),
  },
);

/**
 * Response Public Categories Api V1 Public Categories  Tenant Slug  Get
 *
 * Successful Response
 */
export const zPublicCategoriesApiV1PublicCategoriesTenantSlugGetResponse =
  z.array(zCategoryResponse);

export const zPublicCollectionsApiV1PublicCollectionsTenantSlugGetPath =
  z.object({
    tenant_slug: z.string(),
  });

/**
 * Response Public Collections Api V1 Public Collections  Tenant Slug  Get
 *
 * Successful Response
 */
export const zPublicCollectionsApiV1PublicCollectionsTenantSlugGetResponse =
  z.array(zCollectionResponse);

export const zListStorefrontProductsApiV1StorefrontTenantSlugProductsGetPath =
  z.object({
    tenant_slug: z.string(),
  });

export const zListStorefrontProductsApiV1StorefrontTenantSlugProductsGetQuery =
  z.object({
    page: z.number().int().gte(1).optional().default(1),
    page_size: z.number().int().gte(1).lte(100).optional().default(20),
    category: z.string().nullish(),
    collection: z.string().nullish(),
    q: z.string().nullish(),
  });

/**
 * Successful Response
 */
export const zListStorefrontProductsApiV1StorefrontTenantSlugProductsGetResponse =
  zPaginatedResponseStorefrontProductResponse;

export const zGetStorefrontProductApiV1StorefrontTenantSlugProductsProductSlugGetPath =
  z.object({
    tenant_slug: z.string(),
    product_slug: z.string(),
  });

/**
 * Successful Response
 */
export const zGetStorefrontProductApiV1StorefrontTenantSlugProductsProductSlugGetResponse =
  zStorefrontProductResponse;

export const zGetTenantSettingsApiV1StorefrontTenantSlugSettingsGetPath =
  z.object({
    tenant_slug: z.string(),
  });

/**
 * Successful Response
 */
export const zGetTenantSettingsApiV1StorefrontTenantSlugSettingsGetResponse =
  zTenantSettingsResponse;

export const zCreateCartApiV1StorefrontTenantSlugCartsPostBody =
  zCartAddItemRequest;

export const zCreateCartApiV1StorefrontTenantSlugCartsPostPath = z.object({
  tenant_slug: z.string(),
});

/**
 * Successful Response
 */
export const zCreateCartApiV1StorefrontTenantSlugCartsPostResponse =
  zCartResponse;

export const zClearCartApiV1StorefrontTenantSlugCartsCartIdDeletePath =
  z.object({
    tenant_slug: z.string(),
    cart_id: z.string().uuid(),
  });

/**
 * Successful Response
 */
export const zClearCartApiV1StorefrontTenantSlugCartsCartIdDeleteResponse =
  z.void();

export const zGetCartApiV1StorefrontTenantSlugCartsCartIdGetPath = z.object({
  tenant_slug: z.string(),
  cart_id: z.string().uuid(),
});

/**
 * Successful Response
 */
export const zGetCartApiV1StorefrontTenantSlugCartsCartIdGetResponse =
  zCartResponse;

export const zAddCartItemApiV1StorefrontTenantSlugCartsCartIdItemsPostBody =
  zCartAddItemRequest;

export const zAddCartItemApiV1StorefrontTenantSlugCartsCartIdItemsPostPath =
  z.object({
    tenant_slug: z.string(),
    cart_id: z.string().uuid(),
  });

/**
 * Successful Response
 */
export const zAddCartItemApiV1StorefrontTenantSlugCartsCartIdItemsPostResponse =
  zCartResponse;

export const zRemoveCartItemApiV1StorefrontTenantSlugCartsCartIdItemsItemIdDeletePath =
  z.object({
    tenant_slug: z.string(),
    cart_id: z.string().uuid(),
    item_id: z.string().uuid(),
  });

/**
 * Successful Response
 */
export const zRemoveCartItemApiV1StorefrontTenantSlugCartsCartIdItemsItemIdDeleteResponse =
  zCartResponse;

export const zUpdateCartItemApiV1StorefrontTenantSlugCartsCartIdItemsItemIdPatchBody =
  zCartUpdateItemRequest;

export const zUpdateCartItemApiV1StorefrontTenantSlugCartsCartIdItemsItemIdPatchPath =
  z.object({
    tenant_slug: z.string(),
    cart_id: z.string().uuid(),
    item_id: z.string().uuid(),
  });

/**
 * Successful Response
 */
export const zUpdateCartItemApiV1StorefrontTenantSlugCartsCartIdItemsItemIdPatchResponse =
  zCartResponse;

export const zCheckoutApiV1StorefrontTenantSlugCartsCartIdCheckoutPostBody =
  zCheckoutRequest;

export const zCheckoutApiV1StorefrontTenantSlugCartsCartIdCheckoutPostPath =
  z.object({
    tenant_slug: z.string(),
    cart_id: z.string().uuid(),
  });

/**
 * Successful Response
 */
export const zCheckoutApiV1StorefrontTenantSlugCartsCartIdCheckoutPostResponse =
  zOrderResponse;

/**
 * Response List Tenants Api V1 Tenants  Get
 *
 * Successful Response
 */
export const zListTenantsApiV1TenantsGetResponse = z.array(zTenantResponse);

export const zCreateTenantApiV1TenantsPostBody = zTenantCreate;

/**
 * Successful Response
 */
export const zCreateTenantApiV1TenantsPostResponse = zTenantResponse;

export const zDeleteTenantApiV1TenantsTenantIdDeletePath = z.object({
  tenant_id: z.string().uuid(),
});

/**
 * Successful Response
 */
export const zDeleteTenantApiV1TenantsTenantIdDeleteResponse = z.void();

export const zGetTenantApiV1TenantsTenantIdGetPath = z.object({
  tenant_id: z.string().uuid(),
});

/**
 * Successful Response
 */
export const zGetTenantApiV1TenantsTenantIdGetResponse = zTenantResponse;

export const zUpdateTenantApiV1TenantsTenantIdPutBody = zTenantUpdate;

export const zUpdateTenantApiV1TenantsTenantIdPutPath = z.object({
  tenant_id: z.string().uuid(),
});

/**
 * Successful Response
 */
export const zUpdateTenantApiV1TenantsTenantIdPutResponse = zTenantResponse;

export const zListProductsApiV1ProductsGetHeaders = z.object({
  "X-Tenant-ID": z.string().nullish(),
  authorization: z.string().nullish(),
});

/**
 * Response List Products Api V1 Products  Get
 *
 * Successful Response
 */
export const zListProductsApiV1ProductsGetResponse = z.array(zProductResponse);

export const zCreateProductApiV1ProductsPostBody = zProductCreate;

export const zCreateProductApiV1ProductsPostHeaders = z.object({
  "X-Tenant-ID": z.string().nullish(),
  authorization: z.string().nullish(),
});

/**
 * Successful Response
 */
export const zCreateProductApiV1ProductsPostResponse = zProductResponse;

export const zDeleteProductApiV1ProductsProductIdDeleteHeaders = z.object({
  "X-Tenant-ID": z.string().nullish(),
  authorization: z.string().nullish(),
});

export const zDeleteProductApiV1ProductsProductIdDeletePath = z.object({
  product_id: z.string().uuid(),
});

/**
 * Successful Response
 */
export const zDeleteProductApiV1ProductsProductIdDeleteResponse = z.void();

export const zGetProductApiV1ProductsProductIdGetHeaders = z.object({
  "X-Tenant-ID": z.string().nullish(),
  authorization: z.string().nullish(),
});

export const zGetProductApiV1ProductsProductIdGetPath = z.object({
  product_id: z.string().uuid(),
});

/**
 * Successful Response
 */
export const zGetProductApiV1ProductsProductIdGetResponse = zProductResponse;

export const zUpdateProductApiV1ProductsProductIdPutBody = zProductUpdate;

export const zUpdateProductApiV1ProductsProductIdPutHeaders = z.object({
  "X-Tenant-ID": z.string().nullish(),
  authorization: z.string().nullish(),
});

export const zUpdateProductApiV1ProductsProductIdPutPath = z.object({
  product_id: z.string().uuid(),
});

/**
 * Successful Response
 */
export const zUpdateProductApiV1ProductsProductIdPutResponse = zProductResponse;

export const zListVariantsApiV1ProductsProductIdVariantsGetHeaders = z.object({
  "X-Tenant-ID": z.string().nullish(),
  authorization: z.string().nullish(),
});

export const zListVariantsApiV1ProductsProductIdVariantsGetPath = z.object({
  product_id: z.string().uuid(),
});

/**
 * Response List Variants Api V1 Products  Product Id  Variants Get
 *
 * Successful Response
 */
export const zListVariantsApiV1ProductsProductIdVariantsGetResponse =
  z.array(zVariantResponse);

export const zCreateVariantApiV1ProductsProductIdVariantsPostBody =
  zVariantCreate;

export const zCreateVariantApiV1ProductsProductIdVariantsPostHeaders = z.object(
  {
    "X-Tenant-ID": z.string().nullish(),
    authorization: z.string().nullish(),
  },
);

export const zCreateVariantApiV1ProductsProductIdVariantsPostPath = z.object({
  product_id: z.string().uuid(),
});

/**
 * Successful Response
 */
export const zCreateVariantApiV1ProductsProductIdVariantsPostResponse =
  zVariantResponse;

export const zDeleteVariantApiV1ProductsProductIdVariantsVariantIdDeleteHeaders =
  z.object({
    "X-Tenant-ID": z.string().nullish(),
    authorization: z.string().nullish(),
  });

export const zDeleteVariantApiV1ProductsProductIdVariantsVariantIdDeletePath =
  z.object({
    product_id: z.string().uuid(),
    variant_id: z.string().uuid(),
  });

/**
 * Successful Response
 */
export const zDeleteVariantApiV1ProductsProductIdVariantsVariantIdDeleteResponse =
  z.void();

export const zGetVariantApiV1ProductsProductIdVariantsVariantIdGetHeaders =
  z.object({
    "X-Tenant-ID": z.string().nullish(),
    authorization: z.string().nullish(),
  });

export const zGetVariantApiV1ProductsProductIdVariantsVariantIdGetPath =
  z.object({
    product_id: z.string().uuid(),
    variant_id: z.string().uuid(),
  });

/**
 * Successful Response
 */
export const zGetVariantApiV1ProductsProductIdVariantsVariantIdGetResponse =
  zVariantResponse;

export const zUpdateVariantApiV1ProductsProductIdVariantsVariantIdPutBody =
  zVariantUpdate;

export const zUpdateVariantApiV1ProductsProductIdVariantsVariantIdPutHeaders =
  z.object({
    "X-Tenant-ID": z.string().nullish(),
    authorization: z.string().nullish(),
  });

export const zUpdateVariantApiV1ProductsProductIdVariantsVariantIdPutPath =
  z.object({
    product_id: z.string().uuid(),
    variant_id: z.string().uuid(),
  });

/**
 * Successful Response
 */
export const zUpdateVariantApiV1ProductsProductIdVariantsVariantIdPutResponse =
  zVariantResponse;

export const zListOrdersApiV1OrdersGetHeaders = z.object({
  "X-Tenant-ID": z.string().nullish(),
  authorization: z.string().nullish(),
});

export const zListOrdersApiV1OrdersGetQuery = z.object({
  status: z.string().nullish(),
  payment_status: z.string().nullish(),
  search: z.string().nullish(),
  page: z.number().int().gte(1).optional().default(1),
  page_size: z.number().int().gte(1).lte(100).optional().default(20),
});

/**
 * Response List Orders Api V1 Orders  Get
 *
 * Successful Response
 */
export const zListOrdersApiV1OrdersGetResponse = z.array(zOrderResponse);

export const zCreateOrderApiV1OrdersPostBody = zOrderCreate;

export const zCreateOrderApiV1OrdersPostHeaders = z.object({
  "X-Tenant-ID": z.string().nullish(),
  authorization: z.string().nullish(),
});

/**
 * Successful Response
 */
export const zCreateOrderApiV1OrdersPostResponse = zOrderResponse;

export const zGetOrderApiV1OrdersOrderIdGetHeaders = z.object({
  "X-Tenant-ID": z.string().nullish(),
  authorization: z.string().nullish(),
});

export const zGetOrderApiV1OrdersOrderIdGetPath = z.object({
  order_id: z.string().uuid(),
});

/**
 * Successful Response
 */
export const zGetOrderApiV1OrdersOrderIdGetResponse = zOrderResponse;

export const zPatchOrderApiV1OrdersOrderIdPatchBody = zOrderUpdate;

export const zPatchOrderApiV1OrdersOrderIdPatchHeaders = z.object({
  "X-Tenant-ID": z.string().nullish(),
  authorization: z.string().nullish(),
});

export const zPatchOrderApiV1OrdersOrderIdPatchPath = z.object({
  order_id: z.string().uuid(),
});

/**
 * Successful Response
 */
export const zPatchOrderApiV1OrdersOrderIdPatchResponse = zOrderResponse;

export const zUpdateOrderApiV1OrdersOrderIdPutBody = zOrderUpdate;

export const zUpdateOrderApiV1OrdersOrderIdPutHeaders = z.object({
  "X-Tenant-ID": z.string().nullish(),
  authorization: z.string().nullish(),
});

export const zUpdateOrderApiV1OrdersOrderIdPutPath = z.object({
  order_id: z.string().uuid(),
});

/**
 * Successful Response
 */
export const zUpdateOrderApiV1OrdersOrderIdPutResponse = zOrderResponse;

export const zGetOrderPurchaseOrdersApiV1OrdersOrderIdPurchaseOrdersGetHeaders =
  z.object({
    "X-Tenant-ID": z.string().nullish(),
    authorization: z.string().nullish(),
  });

export const zGetOrderPurchaseOrdersApiV1OrdersOrderIdPurchaseOrdersGetPath =
  z.object({
    order_id: z.string().uuid(),
  });

/**
 * Response Get Order Purchase Orders Api V1 Orders  Order Id  Purchase Orders Get
 *
 * Successful Response
 */
export const zGetOrderPurchaseOrdersApiV1OrdersOrderIdPurchaseOrdersGetResponse =
  z.array(zAssociatedPoResponse);

export const zSvixWebhookWebhooksSvixPostHeaders = z.object({
  "Svix-Signature": z.string().optional(),
  "Svix-Timestamp": z.string().optional(),
});

export const zShopifyWebhookWebhooksShopifyPostHeaders = z.object({
  "X-Shopify-Shop-Domain": z.string().optional(),
  "X-Shopify-Hmac-Sha256": z.string().optional(),
  "X-Shopify-Topic": z.string().optional(),
});

export const zRegisterAuthRegisterPostBody = zRegisterRequest;

/**
 * Successful Response
 */
export const zRegisterAuthRegisterPostResponse = zRegisterResponse;

export const zLoginAuthLoginPostBody = zLoginRequest;

/**
 * Successful Response
 */
export const zLoginAuthLoginPostResponse = zLoginResponse;

/**
 * Successful Response
 */
export const zRefreshTokenAuthRefreshPostResponse = zLoginResponse;

/**
 * Successful Response
 */
export const zLogoutAuthLogoutPostResponse = z.void();

export const zRegisterAdminAuthRegisterPostBody = zAdminRegisterRequest;

/**
 * Successful Response
 */
export const zRegisterAdminAuthRegisterPostResponse = zAdminUserResponse;

export const zLoginAdminAuthLoginPostBody = zAdminLoginRequest;

/**
 * Successful Response
 */
export const zLoginAdminAuthLoginPostResponse = zAdminTokenResponse;

export const zRefreshAdminAuthRefreshPostBody = zAdminRefreshRequest;

/**
 * Successful Response
 */
export const zRefreshAdminAuthRefreshPostResponse = zAdminTokenResponse;

/**
 * Successful Response
 */
export const zLogoutAdminAuthLogoutPostResponse = z.void();

/**
 * Successful Response
 */
export const zMeAdminAuthMeGetResponse = zAdminUserResponse;

/**
 * Successful Response
 */
export const zVerifyAdminAuthVerifyPostResponse = zAdminUserResponse;

export const zCreateProductImageApiV1ProductsProductIdImagesPostBody =
  zProductImageCreate;

export const zCreateProductImageApiV1ProductsProductIdImagesPostHeaders =
  z.object({
    "X-Tenant-ID": z.string().nullish(),
    authorization: z.string().nullish(),
  });

export const zCreateProductImageApiV1ProductsProductIdImagesPostPath = z.object(
  {
    product_id: z.string().uuid(),
  },
);

/**
 * Successful Response
 */
export const zCreateProductImageApiV1ProductsProductIdImagesPostResponse =
  zProductImageResponse;

export const zDeleteProductImageApiV1ProductImagesImageIdDeleteHeaders =
  z.object({
    "X-Tenant-ID": z.string().nullish(),
    authorization: z.string().nullish(),
  });

export const zDeleteProductImageApiV1ProductImagesImageIdDeletePath = z.object({
  image_id: z.string().uuid(),
});

/**
 * Successful Response
 */
export const zDeleteProductImageApiV1ProductImagesImageIdDeleteResponse =
  z.void();

export const zUpdateProductImageApiV1ProductImagesImageIdPatchBody =
  zProductImageUpdate;

export const zUpdateProductImageApiV1ProductImagesImageIdPatchHeaders =
  z.object({
    "X-Tenant-ID": z.string().nullish(),
    authorization: z.string().nullish(),
  });

export const zUpdateProductImageApiV1ProductImagesImageIdPatchPath = z.object({
  image_id: z.string().uuid(),
});

/**
 * Successful Response
 */
export const zUpdateProductImageApiV1ProductImagesImageIdPatchResponse =
  zProductImageResponse;

export const zListCategoriesApiV1CategoriesGetHeaders = z.object({
  "X-Tenant-ID": z.string().nullish(),
  authorization: z.string().nullish(),
});

export const zListCategoriesApiV1CategoriesGetQuery = z.object({
  include_inactive: z.boolean().optional().default(false),
});

/**
 * Response List Categories Api V1 Categories  Get
 *
 * Successful Response
 */
export const zListCategoriesApiV1CategoriesGetResponse =
  z.array(zCategoryResponse);

export const zCreateCategoryApiV1CategoriesPostBody = zCategoryCreate;

export const zCreateCategoryApiV1CategoriesPostHeaders = z.object({
  "X-Tenant-ID": z.string().nullish(),
  authorization: z.string().nullish(),
});

/**
 * Successful Response
 */
export const zCreateCategoryApiV1CategoriesPostResponse = zCategoryResponse;

export const zDeleteCategoryApiV1CategoriesCategoryIdDeleteHeaders = z.object({
  "X-Tenant-ID": z.string().nullish(),
  authorization: z.string().nullish(),
});

export const zDeleteCategoryApiV1CategoriesCategoryIdDeletePath = z.object({
  category_id: z.string().uuid(),
});

export const zUpdateCategoryApiV1CategoriesCategoryIdPutBody = zCategoryUpdate;

export const zUpdateCategoryApiV1CategoriesCategoryIdPutHeaders = z.object({
  "X-Tenant-ID": z.string().nullish(),
  authorization: z.string().nullish(),
});

export const zUpdateCategoryApiV1CategoriesCategoryIdPutPath = z.object({
  category_id: z.string().uuid(),
});

/**
 * Successful Response
 */
export const zUpdateCategoryApiV1CategoriesCategoryIdPutResponse =
  zCategoryResponse;

export const zListCollectionsApiV1CollectionsGetHeaders = z.object({
  "X-Tenant-ID": z.string().nullish(),
  authorization: z.string().nullish(),
});

export const zListCollectionsApiV1CollectionsGetQuery = z.object({
  include_inactive: z.boolean().optional().default(false),
});

/**
 * Response List Collections Api V1 Collections  Get
 *
 * Successful Response
 */
export const zListCollectionsApiV1CollectionsGetResponse =
  z.array(zCollectionResponse);

export const zCreateCollectionApiV1CollectionsPostBody = zCollectionCreate;

export const zCreateCollectionApiV1CollectionsPostHeaders = z.object({
  "X-Tenant-ID": z.string().nullish(),
  authorization: z.string().nullish(),
});

/**
 * Successful Response
 */
export const zCreateCollectionApiV1CollectionsPostResponse =
  zCollectionResponse;

export const zDeleteCollectionApiV1CollectionsCollectionIdDeleteHeaders =
  z.object({
    "X-Tenant-ID": z.string().nullish(),
    authorization: z.string().nullish(),
  });

export const zDeleteCollectionApiV1CollectionsCollectionIdDeletePath = z.object(
  {
    collection_id: z.string().uuid(),
  },
);

export const zUpdateCollectionApiV1CollectionsCollectionIdPutBody =
  zCollectionUpdate;

export const zUpdateCollectionApiV1CollectionsCollectionIdPutHeaders = z.object(
  {
    "X-Tenant-ID": z.string().nullish(),
    authorization: z.string().nullish(),
  },
);

export const zUpdateCollectionApiV1CollectionsCollectionIdPutPath = z.object({
  collection_id: z.string().uuid(),
});

/**
 * Successful Response
 */
export const zUpdateCollectionApiV1CollectionsCollectionIdPutResponse =
  zCollectionResponse;

export const zListCollectionProductsApiV1CollectionsCollectionIdProductsGetHeaders =
  z.object({
    "X-Tenant-ID": z.string().nullish(),
    authorization: z.string().nullish(),
  });

export const zListCollectionProductsApiV1CollectionsCollectionIdProductsGetPath =
  z.object({
    collection_id: z.string().uuid(),
  });

/**
 * Response List Collection Products Api V1 Collections  Collection Id  Products Get
 *
 * Successful Response
 */
export const zListCollectionProductsApiV1CollectionsCollectionIdProductsGetResponse =
  z.array(z.record(z.unknown()));

/**
 * Body
 */
export const zAddProductsToCollectionApiV1CollectionsCollectionIdProductsPostBody =
  z.record(z.unknown());

export const zAddProductsToCollectionApiV1CollectionsCollectionIdProductsPostHeaders =
  z.object({
    "X-Tenant-ID": z.string().nullish(),
    authorization: z.string().nullish(),
  });

export const zAddProductsToCollectionApiV1CollectionsCollectionIdProductsPostPath =
  z.object({
    collection_id: z.string().uuid(),
  });

export const zRemoveProductFromCollectionApiV1CollectionsCollectionIdProductsProductIdDeleteHeaders =
  z.object({
    "X-Tenant-ID": z.string().nullish(),
    authorization: z.string().nullish(),
  });

export const zRemoveProductFromCollectionApiV1CollectionsCollectionIdProductsProductIdDeletePath =
  z.object({
    collection_id: z.string().uuid(),
    product_id: z.string().uuid(),
  });

export const zListCustomersApiV1CustomersGetHeaders = z.object({
  "X-Tenant-ID": z.string().nullish(),
  authorization: z.string().nullish(),
});

export const zListCustomersApiV1CustomersGetQuery = z.object({
  page: z.number().int().gte(1).optional().default(1),
  per_page: z.number().int().gte(1).lte(100).optional().default(20),
  search: z.string().nullish(),
});

export const zGetCustomerApiV1CustomersCustomerIdGetHeaders = z.object({
  "X-Tenant-ID": z.string().nullish(),
  authorization: z.string().nullish(),
});

export const zGetCustomerApiV1CustomersCustomerIdGetPath = z.object({
  customer_id: z.string().uuid(),
});

/**
 * Successful Response
 */
export const zGetCustomerApiV1CustomersCustomerIdGetResponse =
  zCustomerDetailResponse;

export const zDashboardSummaryApiV1AdminDashboardSummaryGetHeaders = z.object({
  "X-Tenant-ID": z.string().nullish(),
  authorization: z.string().nullish(),
});

/**
 * Successful Response
 */
export const zDashboardSummaryApiV1AdminDashboardSummaryGetResponse =
  zDashboardSummaryResponse;

export const zGetStatsApiV1InventoryStatsGetHeaders = z.object({
  "X-Tenant-ID": z.string().nullish(),
  authorization: z.string().nullish(),
});

/**
 * Successful Response
 */
export const zGetStatsApiV1InventoryStatsGetResponse = zInventoryStatsResponse;

export const zListItemsApiV1InventoryGetHeaders = z.object({
  "X-Tenant-ID": z.string().nullish(),
  authorization: z.string().nullish(),
});

export const zListItemsApiV1InventoryGetQuery = z.object({
  q: z.string().nullish(),
  status: z.string().nullish(),
  page: z.number().int().gte(1).optional().default(1),
  page_size: z.number().int().gte(1).lte(100).optional().default(20),
});

/**
 * Successful Response
 */
export const zListItemsApiV1InventoryGetResponse =
  zPaginatedResponseInventoryItemResponse;

export const zCreateItemApiV1InventoryPostBody = zInventoryItemCreateInput;

export const zCreateItemApiV1InventoryPostHeaders = z.object({
  "X-Tenant-ID": z.string().nullish(),
  authorization: z.string().nullish(),
});

/**
 * Successful Response
 */
export const zCreateItemApiV1InventoryPostResponse = zInventoryItemResponse;

export const zDeleteItemApiV1InventoryItemIdDeleteHeaders = z.object({
  "X-Tenant-ID": z.string().nullish(),
  authorization: z.string().nullish(),
});

export const zDeleteItemApiV1InventoryItemIdDeletePath = z.object({
  item_id: z.string().uuid(),
});

/**
 * Successful Response
 */
export const zDeleteItemApiV1InventoryItemIdDeleteResponse = z.void();

export const zGetItemApiV1InventoryItemIdGetHeaders = z.object({
  "X-Tenant-ID": z.string().nullish(),
  authorization: z.string().nullish(),
});

export const zGetItemApiV1InventoryItemIdGetPath = z.object({
  item_id: z.string().uuid(),
});

/**
 * Successful Response
 */
export const zGetItemApiV1InventoryItemIdGetResponse = zInventoryItemResponse;

export const zUpdateItemApiV1InventoryItemIdPatchBody =
  zInventoryItemPatchInput;

export const zUpdateItemApiV1InventoryItemIdPatchHeaders = z.object({
  "X-Tenant-ID": z.string().nullish(),
  authorization: z.string().nullish(),
});

export const zUpdateItemApiV1InventoryItemIdPatchPath = z.object({
  item_id: z.string().uuid(),
});

/**
 * Successful Response
 */
export const zUpdateItemApiV1InventoryItemIdPatchResponse =
  zInventoryItemResponse;

export const zListSuppliersApiV1SuppliersGetHeaders = z.object({
  "X-Tenant-ID": z.string().nullish(),
  authorization: z.string().nullish(),
});

export const zListSuppliersApiV1SuppliersGetQuery = z.object({
  page: z.number().int().gte(1).optional().default(1),
  page_size: z.number().int().gte(1).lte(100).optional().default(20),
});

/**
 * Successful Response
 */
export const zListSuppliersApiV1SuppliersGetResponse = zSupplierListResponse;

export const zCreateSupplierApiV1SuppliersPostBody = zSupplierCreateInput;

export const zCreateSupplierApiV1SuppliersPostHeaders = z.object({
  "X-Tenant-ID": z.string().nullish(),
  authorization: z.string().nullish(),
});

/**
 * Successful Response
 */
export const zCreateSupplierApiV1SuppliersPostResponse = zSupplierResponse;

export const zDeleteSupplierApiV1SuppliersSupplierIdDeleteHeaders = z.object({
  "X-Tenant-ID": z.string().nullish(),
  authorization: z.string().nullish(),
});

export const zDeleteSupplierApiV1SuppliersSupplierIdDeletePath = z.object({
  supplier_id: z.string().uuid(),
});

/**
 * Successful Response
 */
export const zDeleteSupplierApiV1SuppliersSupplierIdDeleteResponse = z.void();

export const zGetSupplierApiV1SuppliersSupplierIdGetHeaders = z.object({
  "X-Tenant-ID": z.string().nullish(),
  authorization: z.string().nullish(),
});

export const zGetSupplierApiV1SuppliersSupplierIdGetPath = z.object({
  supplier_id: z.string().uuid(),
});

/**
 * Successful Response
 */
export const zGetSupplierApiV1SuppliersSupplierIdGetResponse =
  zSupplierResponse;

export const zUpdateSupplierApiV1SuppliersSupplierIdPatchBody =
  zSupplierPatchInput;

export const zUpdateSupplierApiV1SuppliersSupplierIdPatchHeaders = z.object({
  "X-Tenant-ID": z.string().nullish(),
  authorization: z.string().nullish(),
});

export const zUpdateSupplierApiV1SuppliersSupplierIdPatchPath = z.object({
  supplier_id: z.string().uuid(),
});

/**
 * Successful Response
 */
export const zUpdateSupplierApiV1SuppliersSupplierIdPatchResponse =
  zSupplierResponse;

export const zListPurchaseOrdersApiV1PurchaseOrdersGetHeaders = z.object({
  "X-Tenant-ID": z.string().nullish(),
  authorization: z.string().nullish(),
});

export const zListPurchaseOrdersApiV1PurchaseOrdersGetQuery = z.object({
  status: z.string().nullish(),
  supplier_id: z.string().uuid().nullish(),
  page: z.number().int().gte(1).optional().default(1),
  page_size: z.number().int().gte(1).lte(100).optional().default(20),
});

/**
 * Successful Response
 */
export const zListPurchaseOrdersApiV1PurchaseOrdersGetResponse =
  zPurchaseOrderListResponse;

export const zListPendingOrdersApiV1PurchaseOrdersPendingGetHeaders = z.object({
  "X-Tenant-ID": z.string().nullish(),
  authorization: z.string().nullish(),
});

export const zListPendingOrdersApiV1PurchaseOrdersPendingGetQuery = z.object({
  page: z.number().int().gte(1).optional().default(1),
  page_size: z.number().int().gte(1).lte(100).optional().default(20),
});

/**
 * Successful Response
 */
export const zListPendingOrdersApiV1PurchaseOrdersPendingGetResponse =
  zPurchaseOrderListResponse;

export const zGetPurchaseOrderApiV1PurchaseOrdersPoIdGetHeaders = z.object({
  "X-Tenant-ID": z.string().nullish(),
  authorization: z.string().nullish(),
});

export const zGetPurchaseOrderApiV1PurchaseOrdersPoIdGetPath = z.object({
  po_id: z.string().uuid(),
});

/**
 * Successful Response
 */
export const zGetPurchaseOrderApiV1PurchaseOrdersPoIdGetResponse =
  zPurchaseOrderResponse;

export const zUpdatePurchaseOrderApiV1PurchaseOrdersPoIdPatchBody =
  zPurchaseOrderPatchInput;

export const zUpdatePurchaseOrderApiV1PurchaseOrdersPoIdPatchHeaders = z.object(
  {
    "X-Tenant-ID": z.string().nullish(),
    authorization: z.string().nullish(),
  },
);

export const zUpdatePurchaseOrderApiV1PurchaseOrdersPoIdPatchPath = z.object({
  po_id: z.string().uuid(),
});

/**
 * Successful Response
 */
export const zUpdatePurchaseOrderApiV1PurchaseOrdersPoIdPatchResponse =
  zPurchaseOrderResponse;

export const zApprovePurchaseOrderApiV1PurchaseOrdersPoIdApprovePostHeaders =
  z.object({
    "X-Tenant-ID": z.string().nullish(),
    authorization: z.string().nullish(),
  });

export const zApprovePurchaseOrderApiV1PurchaseOrdersPoIdApprovePostPath =
  z.object({
    po_id: z.string().uuid(),
  });

/**
 * Successful Response
 */
export const zApprovePurchaseOrderApiV1PurchaseOrdersPoIdApprovePostResponse =
  zPurchaseOrderResponse;

export const zCancelPurchaseOrderApiV1PurchaseOrdersPoIdCancelPostHeaders =
  z.object({
    "X-Tenant-ID": z.string().nullish(),
    authorization: z.string().nullish(),
  });

export const zCancelPurchaseOrderApiV1PurchaseOrdersPoIdCancelPostPath =
  z.object({
    po_id: z.string().uuid(),
  });

/**
 * Successful Response
 */
export const zCancelPurchaseOrderApiV1PurchaseOrdersPoIdCancelPostResponse =
  zPurchaseOrderResponse;
